
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2019.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xrgb2ycrcb.h"

/*
* The configuration table for devices
*/

XRgb2YCrCb_Config XRgb2YCrCb_ConfigTable[XPAR_XRGB2YCRCB_NUM_INSTANCES] =
{
	{
		XPAR_V_RGB2YCRCB_0_DEVICE_ID,
		XPAR_V_RGB2YCRCB_0_BASEADDR,
		XPAR_V_RGB2YCRCB_0_S_AXIS_VIDEO_FORMAT,
		XPAR_V_RGB2YCRCB_0_M_AXIS_VIDEO_FORMAT,
		XPAR_V_RGB2YCRCB_0_HAS_DEBUG,
		XPAR_V_RGB2YCRCB_0_HAS_INTC_IF,
		XPAR_V_RGB2YCRCB_0_MAX_COLS,
		XPAR_V_RGB2YCRCB_0_ACTIVE_COLS,
		XPAR_V_RGB2YCRCB_0_ACTIVE_ROWS,
		XPAR_V_RGB2YCRCB_0_HAS_CLIP,
		XPAR_V_RGB2YCRCB_0_HAS_CLAMP,
		XPAR_V_RGB2YCRCB_0_ACOEF,
		XPAR_V_RGB2YCRCB_0_BCOEF,
		XPAR_V_RGB2YCRCB_0_CCOEF,
		XPAR_V_RGB2YCRCB_0_DCOEF,
		XPAR_V_RGB2YCRCB_0_YOFFSET,
		XPAR_V_RGB2YCRCB_0_CBOFFSET,
		XPAR_V_RGB2YCRCB_0_CROFFSET,
		XPAR_V_RGB2YCRCB_0_YMAX,
		XPAR_V_RGB2YCRCB_0_YMIN,
		XPAR_V_RGB2YCRCB_0_CBMAX,
		XPAR_V_RGB2YCRCB_0_CBMIN,
		XPAR_V_RGB2YCRCB_0_CRMAX,
		XPAR_V_RGB2YCRCB_0_CRMIN,
		XPAR_V_RGB2YCRCB_0_S_AXI_CLK_FREQ_HZ,
		XPAR_V_RGB2YCRCB_0_STANDARD_SEL,
		XPAR_V_RGB2YCRCB_0_OUTPUT_RANGE
	}
};


