// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_d92b_hsc_0_hscale_core_polyphas (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        SrcImg_V_val_0_V_dout,
        SrcImg_V_val_0_V_empty_n,
        SrcImg_V_val_0_V_read,
        SrcImg_V_val_1_V_dout,
        SrcImg_V_val_1_V_empty_n,
        SrcImg_V_val_1_V_read,
        SrcImg_V_val_2_V_dout,
        SrcImg_V_val_2_V_empty_n,
        SrcImg_V_val_2_V_read,
        Height_dout,
        Height_empty_n,
        Height_read,
        InPixels_dout,
        InPixels_empty_n,
        InPixels_read,
        OutPixels_dout,
        OutPixels_empty_n,
        OutPixels_read,
        hfltCoeff_address0,
        hfltCoeff_ce0,
        hfltCoeff_q0,
        arrPhasesH_V_address0,
        arrPhasesH_V_ce0,
        arrPhasesH_V_q0,
        OutImg_V_val_0_V_din,
        OutImg_V_val_0_V_full_n,
        OutImg_V_val_0_V_write,
        OutImg_V_val_1_V_din,
        OutImg_V_val_1_V_full_n,
        OutImg_V_val_1_V_write,
        OutImg_V_val_2_V_din,
        OutImg_V_val_2_V_full_n,
        OutImg_V_val_2_V_write,
        Height_out_din,
        Height_out_full_n,
        Height_out_write,
        OutPixels_out_din,
        OutPixels_out_full_n,
        OutPixels_out_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_pp0_stage0 = 9'd128;
parameter    ap_ST_fsm_state23 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] SrcImg_V_val_0_V_dout;
input   SrcImg_V_val_0_V_empty_n;
output   SrcImg_V_val_0_V_read;
input  [7:0] SrcImg_V_val_1_V_dout;
input   SrcImg_V_val_1_V_empty_n;
output   SrcImg_V_val_1_V_read;
input  [7:0] SrcImg_V_val_2_V_dout;
input   SrcImg_V_val_2_V_empty_n;
output   SrcImg_V_val_2_V_read;
input  [15:0] Height_dout;
input   Height_empty_n;
output   Height_read;
input  [15:0] InPixels_dout;
input   InPixels_empty_n;
output   InPixels_read;
input  [15:0] OutPixels_dout;
input   OutPixels_empty_n;
output   OutPixels_read;
output  [8:0] hfltCoeff_address0;
output   hfltCoeff_ce0;
input  [15:0] hfltCoeff_q0;
output  [11:0] arrPhasesH_V_address0;
output   arrPhasesH_V_ce0;
input  [8:0] arrPhasesH_V_q0;
output  [7:0] OutImg_V_val_0_V_din;
input   OutImg_V_val_0_V_full_n;
output   OutImg_V_val_0_V_write;
output  [7:0] OutImg_V_val_1_V_din;
input   OutImg_V_val_1_V_full_n;
output   OutImg_V_val_1_V_write;
output  [7:0] OutImg_V_val_2_V_din;
input   OutImg_V_val_2_V_full_n;
output   OutImg_V_val_2_V_write;
output  [15:0] Height_out_din;
input   Height_out_full_n;
output   Height_out_write;
output  [15:0] OutPixels_out_din;
input   OutPixels_out_full_n;
output   OutPixels_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg SrcImg_V_val_0_V_read;
reg SrcImg_V_val_1_V_read;
reg SrcImg_V_val_2_V_read;
reg Height_read;
reg InPixels_read;
reg OutPixels_read;
reg hfltCoeff_ce0;
reg arrPhasesH_V_ce0;
reg OutImg_V_val_0_V_write;
reg OutImg_V_val_1_V_write;
reg OutImg_V_val_2_V_write;
reg Height_out_write;
reg OutPixels_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    SrcImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln619_reg_1875;
reg   [0:0] icmp_ln628_reg_1907;
reg    SrcImg_V_val_1_V_blk_n;
reg    SrcImg_V_val_2_V_blk_n;
reg    Height_blk_n;
reg    InPixels_blk_n;
reg    OutPixels_blk_n;
reg    OutImg_V_val_0_V_blk_n;
reg    ap_enable_reg_pp0_iter14;
reg   [0:0] icmp_ln665_reg_1827;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter13_reg;
reg   [0:0] and_ln705_reg_1921;
reg   [0:0] and_ln705_reg_1921_pp0_iter13_reg;
reg    OutImg_V_val_1_V_blk_n;
reg    OutImg_V_val_2_V_blk_n;
reg    Height_out_blk_n;
reg    OutPixels_out_blk_n;
reg   [15:0] x_0_i_reg_642;
reg   [15:0] x_0_i_reg_642_pp0_iter1_reg;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state8_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
wire    io_acc_block_signal_op269;
reg    ap_predicate_op269_read_state11;
reg    ap_block_state11_pp0_stage0_iter3;
wire    ap_block_state12_pp0_stage0_iter4;
wire    ap_block_state13_pp0_stage0_iter5;
wire    ap_block_state14_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
wire    ap_block_state16_pp0_stage0_iter8;
wire    ap_block_state17_pp0_stage0_iter9;
wire    ap_block_state18_pp0_stage0_iter10;
wire    ap_block_state19_pp0_stage0_iter11;
wire    ap_block_state20_pp0_stage0_iter12;
wire    ap_block_state21_pp0_stage0_iter13;
wire    io_acc_block_signal_op321;
reg    ap_predicate_op321_write_state22;
reg    ap_block_state22_pp0_stage0_iter14;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] ReadEn_0_i_reg_654;
reg   [15:0] xReadPos_0_i_reg_665;
reg   [31:0] ReadEn_1_i_reg_676;
reg   [15:0] xReadPos_2_i_reg_688;
reg   [15:0] Height_read_reg_1494;
reg    ap_block_state1;
reg   [15:0] InPixels_read_reg_1499;
reg   [15:0] OutPixels_read_reg_1506;
wire   [15:0] TotalPixels_fu_748_p3;
reg   [15:0] TotalPixels_reg_1512;
wire    ap_CS_fsm_state2;
wire   [15:0] LoopSize_fu_754_p2;
reg   [15:0] LoopSize_reg_1517;
wire   [6:0] i_fu_766_p2;
reg   [6:0] i_reg_1525;
wire    ap_CS_fsm_state3;
wire   [10:0] zext_ln586_1_fu_792_p1;
reg   [10:0] zext_ln586_1_reg_1530;
wire   [0:0] icmp_ln580_fu_760_p2;
reg   [5:0] FiltCoeff_0_0_addr_reg_1535;
reg   [5:0] FiltCoeff_1_0_addr_reg_1540;
reg   [5:0] FiltCoeff_2_0_addr_reg_1545;
reg   [5:0] FiltCoeff_3_0_addr_reg_1550;
reg   [5:0] FiltCoeff_4_0_addr_reg_1555;
reg   [5:0] FiltCoeff_5_0_addr_reg_1560;
reg   [5:0] FiltCoeff_6_0_addr_reg_1565;
reg   [5:0] FiltCoeff_7_0_addr_reg_1570;
wire   [15:0] add_ln592_fu_796_p2;
reg   [15:0] add_ln592_reg_1782;
wire   [16:0] zext_ln628_fu_801_p1;
reg   [16:0] zext_ln628_reg_1787;
wire   [3:0] j_fu_810_p2;
reg   [3:0] j_reg_1795;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln583_fu_804_p2;
wire   [2:0] trunc_ln586_fu_830_p1;
reg   [2:0] trunc_ln586_reg_1805;
wire   [0:0] icmp_ln592_fu_834_p2;
wire    ap_CS_fsm_state7;
wire   [15:0] y_fu_839_p2;
reg   [15:0] y_reg_1813;
wire   [0:0] icmp_ln608_fu_845_p2;
reg   [0:0] icmp_ln608_reg_1818;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter1_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter2_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter3_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter4_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter5_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter6_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter7_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter8_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter9_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter10_reg;
reg   [0:0] icmp_ln608_reg_1818_pp0_iter11_reg;
wire   [15:0] x_fu_850_p2;
reg   [15:0] x_reg_1822;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln665_fu_856_p2;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter1_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter2_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter3_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter4_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter5_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter6_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter7_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter8_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter9_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter10_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter11_reg;
reg   [0:0] icmp_ln665_reg_1827_pp0_iter12_reg;
reg   [7:0] PixArray_8_val_0_V_2_reg_1836;
reg   [7:0] PixArray_8_val_1_V_2_reg_1849;
reg   [7:0] PixArray_8_val_2_V_2_reg_1862;
wire   [0:0] icmp_ln619_fu_888_p2;
wire   [0:0] icmp_ln625_fu_904_p2;
reg   [0:0] icmp_ln625_reg_1879;
wire   [0:0] icmp_ln628_fu_920_p2;
wire   [5:0] trunc_ln681_fu_925_p1;
reg   [5:0] trunc_ln681_reg_1911;
reg   [5:0] trunc_ln681_reg_1911_pp0_iter3_reg;
wire   [1:0] p_Result_1_i_fu_929_p4;
reg   [1:0] p_Result_1_i_reg_1916;
reg   [1:0] p_Result_1_i_reg_1916_pp0_iter3_reg;
wire   [0:0] and_ln705_fu_978_p2;
reg   [0:0] and_ln705_reg_1921_pp0_iter3_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter4_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter5_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter6_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter7_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter8_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter9_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter10_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter11_reg;
reg   [0:0] and_ln705_reg_1921_pp0_iter12_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_condition_pp0_exit_iter2_state10;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg   [5:0] FiltCoeff_0_0_address0;
reg    FiltCoeff_0_0_ce0;
reg    FiltCoeff_0_0_we0;
wire   [15:0] FiltCoeff_0_0_q0;
reg   [5:0] FiltCoeff_1_0_address0;
reg    FiltCoeff_1_0_ce0;
reg    FiltCoeff_1_0_we0;
wire   [15:0] FiltCoeff_1_0_q0;
reg   [5:0] FiltCoeff_2_0_address0;
reg    FiltCoeff_2_0_ce0;
reg    FiltCoeff_2_0_we0;
wire   [15:0] FiltCoeff_2_0_q0;
reg   [5:0] FiltCoeff_3_0_address0;
reg    FiltCoeff_3_0_ce0;
reg    FiltCoeff_3_0_we0;
wire   [15:0] FiltCoeff_3_0_q0;
reg   [5:0] FiltCoeff_4_0_address0;
reg    FiltCoeff_4_0_ce0;
reg    FiltCoeff_4_0_we0;
wire   [15:0] FiltCoeff_4_0_q0;
reg   [5:0] FiltCoeff_5_0_address0;
reg    FiltCoeff_5_0_ce0;
reg    FiltCoeff_5_0_we0;
wire   [15:0] FiltCoeff_5_0_q0;
reg   [5:0] FiltCoeff_6_0_address0;
reg    FiltCoeff_6_0_ce0;
reg    FiltCoeff_6_0_we0;
wire   [15:0] FiltCoeff_6_0_q0;
reg   [5:0] FiltCoeff_7_0_address0;
reg    FiltCoeff_7_0_ce0;
reg    FiltCoeff_7_0_we0;
wire   [15:0] FiltCoeff_7_0_q0;
wire    grp_hscale_polyphase_fu_700_ap_start;
wire    grp_hscale_polyphase_fu_700_ap_done;
wire    grp_hscale_polyphase_fu_700_ap_idle;
wire    grp_hscale_polyphase_fu_700_ap_ready;
reg    grp_hscale_polyphase_fu_700_ap_ce;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_0_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_0_ce0;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_1_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_1_ce0;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_2_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_2_ce0;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_3_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_3_ce0;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_4_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_4_ce0;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_5_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_5_ce0;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_6_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_6_ce0;
wire   [5:0] grp_hscale_polyphase_fu_700_FiltCoeff_7_address0;
wire    grp_hscale_polyphase_fu_700_FiltCoeff_7_ce0;
wire   [7:0] grp_hscale_polyphase_fu_700_ap_return_0;
wire   [7:0] grp_hscale_polyphase_fu_700_ap_return_1;
wire   [7:0] grp_hscale_polyphase_fu_700_ap_return_2;
reg    ap_predicate_op307_call_state12;
reg    ap_predicate_op308_call_state13;
reg    ap_predicate_op309_call_state14;
reg    ap_predicate_op310_call_state15;
reg    ap_predicate_op311_call_state16;
reg    ap_predicate_op312_call_state17;
reg    ap_predicate_op313_call_state18;
reg    ap_predicate_op314_call_state19;
reg    ap_predicate_op315_call_state20;
wire    ap_block_state8_pp0_stage0_iter0_ignore_call40;
wire    ap_block_state9_pp0_stage0_iter1_ignore_call40;
wire    ap_block_state10_pp0_stage0_iter2_ignore_call40;
reg    ap_block_state11_pp0_stage0_iter3_ignore_call40;
wire    ap_block_state12_pp0_stage0_iter4_ignore_call40;
wire    ap_block_state13_pp0_stage0_iter5_ignore_call40;
wire    ap_block_state14_pp0_stage0_iter6_ignore_call40;
wire    ap_block_state15_pp0_stage0_iter7_ignore_call40;
wire    ap_block_state16_pp0_stage0_iter8_ignore_call40;
wire    ap_block_state17_pp0_stage0_iter9_ignore_call40;
wire    ap_block_state18_pp0_stage0_iter10_ignore_call40;
wire    ap_block_state19_pp0_stage0_iter11_ignore_call40;
wire    ap_block_state20_pp0_stage0_iter12_ignore_call40;
wire    ap_block_state21_pp0_stage0_iter13_ignore_call40;
reg    ap_block_state22_pp0_stage0_iter14_ignore_call40;
reg    ap_block_pp0_stage0_11001_ignoreCallOp307;
wire   [8:0] grp_reg_ap_uint_9_s_fu_873_ap_return;
reg    grp_reg_ap_uint_9_s_fu_873_ap_ce;
reg    ap_predicate_op158_call_state9;
wire    ap_block_state8_pp0_stage0_iter0_ignore_call34;
wire    ap_block_state9_pp0_stage0_iter1_ignore_call34;
wire    ap_block_state10_pp0_stage0_iter2_ignore_call34;
reg    ap_block_state11_pp0_stage0_iter3_ignore_call34;
wire    ap_block_state12_pp0_stage0_iter4_ignore_call34;
wire    ap_block_state13_pp0_stage0_iter5_ignore_call34;
wire    ap_block_state14_pp0_stage0_iter6_ignore_call34;
wire    ap_block_state15_pp0_stage0_iter7_ignore_call34;
wire    ap_block_state16_pp0_stage0_iter8_ignore_call34;
wire    ap_block_state17_pp0_stage0_iter9_ignore_call34;
wire    ap_block_state18_pp0_stage0_iter10_ignore_call34;
wire    ap_block_state19_pp0_stage0_iter11_ignore_call34;
wire    ap_block_state20_pp0_stage0_iter12_ignore_call34;
wire    ap_block_state21_pp0_stage0_iter13_ignore_call34;
reg    ap_block_state22_pp0_stage0_iter14_ignore_call34;
reg    ap_block_pp0_stage0_11001_ignoreCallOp158;
reg   [6:0] i_0_i_reg_609;
reg   [3:0] j_0_i_reg_620;
wire    ap_CS_fsm_state6;
reg   [15:0] y_0_i_reg_631;
wire    ap_CS_fsm_state23;
reg   [15:0] ap_phi_mux_x_0_i_phi_fu_646_p4;
reg   [31:0] ap_phi_mux_ReadEn_0_i_phi_fu_658_p4;
reg   [15:0] ap_phi_mux_xReadPos_0_i_phi_fu_669_p4;
wire   [31:0] ReadEn_fu_953_p1;
wire   [31:0] ap_phi_reg_pp0_iter2_ReadEn_1_i_reg_676;
wire   [15:0] select_ln698_fu_964_p3;
wire   [15:0] ap_phi_reg_pp0_iter2_xReadPos_2_i_reg_688;
reg    grp_hscale_polyphase_fu_700_ap_start_reg;
reg    ap_predicate_op307_call_state12_state11;
wire   [63:0] zext_ln586_fu_772_p1;
wire   [63:0] zext_ln586_3_fu_825_p1;
wire   [63:0] zext_ln672_fu_868_p1;
reg   [7:0] PixArray_0_val_0_V_1_fu_310;
wire   [7:0] PixArray_0_val_0_V_fu_1056_p3;
reg   [7:0] PixArray_0_val_1_V_1_fu_314;
wire   [7:0] PixArray_0_val_1_V_fu_1062_p3;
reg   [7:0] PixArray_0_val_2_V_1_fu_318;
wire   [7:0] PixArray_0_val_2_V_fu_1068_p3;
reg   [7:0] PixArray_1_val_0_V_1_fu_322;
wire   [7:0] PixArray_1_val_0_V_fu_1074_p3;
reg   [7:0] PixArray_1_val_1_V_1_fu_326;
wire   [7:0] PixArray_1_val_1_V_fu_1080_p3;
reg   [7:0] PixArray_1_val_2_V_1_fu_330;
wire   [7:0] PixArray_1_val_2_V_fu_1086_p3;
reg   [7:0] PixArray_2_val_0_V_1_fu_334;
wire   [7:0] PixArray_2_val_0_V_fu_1092_p3;
reg   [7:0] PixArray_2_val_1_V_1_fu_338;
wire   [7:0] PixArray_2_val_1_V_fu_1098_p3;
reg   [7:0] PixArray_2_val_2_V_1_fu_342;
wire   [7:0] PixArray_2_val_2_V_fu_1104_p3;
reg   [7:0] PixArray_3_val_0_V_1_fu_346;
wire   [7:0] PixArray_3_val_0_V_fu_1110_p3;
reg   [7:0] PixArray_3_val_1_V_1_fu_350;
wire   [7:0] PixArray_3_val_1_V_fu_1116_p3;
reg   [7:0] PixArray_3_val_2_V_1_fu_354;
wire   [7:0] PixArray_3_val_2_V_fu_1122_p3;
reg   [7:0] PixArray_4_val_0_V_1_fu_358;
wire   [7:0] PixArray_4_val_0_V_fu_1128_p3;
reg   [7:0] PixArray_4_val_1_V_1_fu_362;
wire   [7:0] PixArray_4_val_1_V_fu_1134_p3;
reg   [7:0] PixArray_4_val_2_V_1_fu_366;
wire   [7:0] PixArray_4_val_2_V_fu_1140_p3;
reg   [7:0] PixArray_5_val_0_V_1_fu_370;
wire   [7:0] PixArray_5_val_0_V_fu_1146_p3;
reg   [7:0] PixArray_5_val_1_V_1_fu_374;
wire   [7:0] PixArray_5_val_1_V_fu_1152_p3;
reg   [7:0] PixArray_5_val_2_V_1_fu_378;
wire   [7:0] PixArray_5_val_2_V_fu_1158_p3;
reg   [7:0] PixArray_6_val_0_V_1_fu_382;
wire   [7:0] PixArray_6_val_0_V_fu_1164_p3;
reg   [7:0] PixArray_6_val_1_V_1_fu_386;
wire   [7:0] PixArray_6_val_1_V_fu_1170_p3;
reg   [7:0] PixArray_6_val_2_V_1_fu_390;
wire   [7:0] PixArray_6_val_2_V_fu_1176_p3;
reg   [7:0] PixArray_7_val_0_V_1_fu_394;
wire   [7:0] PixArray_7_val_0_V_fu_1182_p3;
reg   [7:0] PixArray_7_val_1_V_1_fu_398;
wire   [7:0] PixArray_7_val_1_V_fu_1188_p3;
reg   [7:0] PixArray_7_val_2_V_1_fu_402;
wire   [7:0] PixArray_7_val_2_V_fu_1194_p3;
reg   [7:0] PixArray_8_val_0_V_fu_406;
reg   [7:0] PixArray_8_val_1_V_fu_410;
reg   [7:0] PixArray_8_val_2_V_fu_414;
reg   [7:0] PixArray_8_val_0_V_1_fu_418;
reg   [7:0] ap_sig_allocacmp_PixArray_8_val_0_V_2;
reg   [7:0] PixArray_8_val_1_V_1_fu_422;
reg   [7:0] ap_sig_allocacmp_PixArray_8_val_1_V_2;
reg   [7:0] PixArray_8_val_2_V_1_fu_426;
reg   [7:0] ap_sig_allocacmp_PixArray_8_val_2_V_2;
reg    ap_block_pp0_stage0_01001;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln214_fu_744_p2;
wire   [9:0] tmp_fu_784_p3;
wire   [10:0] zext_ln586_2_fu_816_p1;
wire   [10:0] add_ln586_fu_820_p2;
wire   [15:0] xbySamples_fu_862_p2;
wire   [14:0] tmp_9_fu_894_p4;
wire   [16:0] zext_ln628_1_fu_910_p1;
wire   [16:0] add_ln628_fu_914_p2;
wire   [0:0] icmp_ln685_fu_947_p2;
wire   [15:0] xReadPos_fu_958_p2;
wire   [0:0] p_Result_2_i_fu_939_p3;
wire   [0:0] icmp_ln705_fu_973_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 grp_hscale_polyphase_fu_700_ap_start_reg = 1'b0;
end

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_0_0_address0),
    .ce0(FiltCoeff_0_0_ce0),
    .we0(FiltCoeff_0_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_0_0_q0)
);

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_1_0_address0),
    .ce0(FiltCoeff_1_0_ce0),
    .we0(FiltCoeff_1_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_1_0_q0)
);

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_2_0_address0),
    .ce0(FiltCoeff_2_0_ce0),
    .we0(FiltCoeff_2_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_2_0_q0)
);

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_3_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_3_0_address0),
    .ce0(FiltCoeff_3_0_ce0),
    .we0(FiltCoeff_3_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_3_0_q0)
);

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_4_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_4_0_address0),
    .ce0(FiltCoeff_4_0_ce0),
    .we0(FiltCoeff_4_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_4_0_q0)
);

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_5_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_5_0_address0),
    .ce0(FiltCoeff_5_0_ce0),
    .we0(FiltCoeff_5_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_5_0_q0)
);

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_6_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_6_0_address0),
    .ce0(FiltCoeff_6_0_ce0),
    .we0(FiltCoeff_6_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_6_0_q0)
);

bd_d92b_hsc_0_hscale_core_polypocq #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
FiltCoeff_7_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FiltCoeff_7_0_address0),
    .ce0(FiltCoeff_7_0_ce0),
    .we0(FiltCoeff_7_0_we0),
    .d0(hfltCoeff_q0),
    .q0(FiltCoeff_7_0_q0)
);

bd_d92b_hsc_0_hscale_polyphase grp_hscale_polyphase_fu_700(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_hscale_polyphase_fu_700_ap_start),
    .ap_done(grp_hscale_polyphase_fu_700_ap_done),
    .ap_idle(grp_hscale_polyphase_fu_700_ap_idle),
    .ap_ready(grp_hscale_polyphase_fu_700_ap_ready),
    .ap_ce(grp_hscale_polyphase_fu_700_ap_ce),
    .FiltCoeff_0_address0(grp_hscale_polyphase_fu_700_FiltCoeff_0_address0),
    .FiltCoeff_0_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_0_ce0),
    .FiltCoeff_0_q0(FiltCoeff_0_0_q0),
    .FiltCoeff_1_address0(grp_hscale_polyphase_fu_700_FiltCoeff_1_address0),
    .FiltCoeff_1_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_1_ce0),
    .FiltCoeff_1_q0(FiltCoeff_1_0_q0),
    .FiltCoeff_2_address0(grp_hscale_polyphase_fu_700_FiltCoeff_2_address0),
    .FiltCoeff_2_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_2_ce0),
    .FiltCoeff_2_q0(FiltCoeff_2_0_q0),
    .FiltCoeff_3_address0(grp_hscale_polyphase_fu_700_FiltCoeff_3_address0),
    .FiltCoeff_3_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_3_ce0),
    .FiltCoeff_3_q0(FiltCoeff_3_0_q0),
    .FiltCoeff_4_address0(grp_hscale_polyphase_fu_700_FiltCoeff_4_address0),
    .FiltCoeff_4_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_4_ce0),
    .FiltCoeff_4_q0(FiltCoeff_4_0_q0),
    .FiltCoeff_5_address0(grp_hscale_polyphase_fu_700_FiltCoeff_5_address0),
    .FiltCoeff_5_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_5_ce0),
    .FiltCoeff_5_q0(FiltCoeff_5_0_q0),
    .FiltCoeff_6_address0(grp_hscale_polyphase_fu_700_FiltCoeff_6_address0),
    .FiltCoeff_6_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_6_ce0),
    .FiltCoeff_6_q0(FiltCoeff_6_0_q0),
    .FiltCoeff_7_address0(grp_hscale_polyphase_fu_700_FiltCoeff_7_address0),
    .FiltCoeff_7_ce0(grp_hscale_polyphase_fu_700_FiltCoeff_7_ce0),
    .FiltCoeff_7_q0(FiltCoeff_7_0_q0),
    .PixArray_0_val_0_V_read(PixArray_0_val_0_V_1_fu_310),
    .PixArray_0_val_1_V_read(PixArray_0_val_1_V_1_fu_314),
    .PixArray_0_val_2_V_read(PixArray_0_val_2_V_1_fu_318),
    .PixArray_1_val_0_V_read(PixArray_1_val_0_V_1_fu_322),
    .PixArray_1_val_1_V_read(PixArray_1_val_1_V_1_fu_326),
    .PixArray_1_val_2_V_read(PixArray_1_val_2_V_1_fu_330),
    .PixArray_2_val_0_V_read(PixArray_2_val_0_V_1_fu_334),
    .PixArray_2_val_1_V_read(PixArray_2_val_1_V_1_fu_338),
    .PixArray_2_val_2_V_read(PixArray_2_val_2_V_1_fu_342),
    .PixArray_3_val_0_V_read(PixArray_3_val_0_V_1_fu_346),
    .PixArray_3_val_1_V_read(PixArray_3_val_1_V_1_fu_350),
    .PixArray_3_val_2_V_read(PixArray_3_val_2_V_1_fu_354),
    .PixArray_4_val_0_V_read(PixArray_4_val_0_V_1_fu_358),
    .PixArray_4_val_1_V_read(PixArray_4_val_1_V_1_fu_362),
    .PixArray_4_val_2_V_read(PixArray_4_val_2_V_1_fu_366),
    .PixArray_5_val_0_V_read(PixArray_5_val_0_V_1_fu_370),
    .PixArray_5_val_1_V_read(PixArray_5_val_1_V_1_fu_374),
    .PixArray_5_val_2_V_read(PixArray_5_val_2_V_1_fu_378),
    .PixArray_6_val_0_V_read(PixArray_6_val_0_V_1_fu_382),
    .PixArray_6_val_1_V_read(PixArray_6_val_1_V_1_fu_386),
    .PixArray_6_val_2_V_read(PixArray_6_val_2_V_1_fu_390),
    .PixArray_7_val_0_V_read(PixArray_7_val_0_V_1_fu_394),
    .PixArray_7_val_1_V_read(PixArray_7_val_1_V_1_fu_398),
    .PixArray_7_val_2_V_read(PixArray_7_val_2_V_1_fu_402),
    .PixArray_8_val_0_V_read(PixArray_8_val_0_V_fu_406),
    .PixArray_8_val_1_V_read(PixArray_8_val_1_V_fu_410),
    .PixArray_8_val_2_V_read(PixArray_8_val_2_V_fu_414),
    .PixArray_9_val_0_V_read(PixArray_8_val_0_V_1_fu_418),
    .PixArray_9_val_1_V_read(PixArray_8_val_1_V_1_fu_422),
    .PixArray_9_val_2_V_read(PixArray_8_val_2_V_1_fu_426),
    .PhasesH_0_read(trunc_ln681_reg_1911_pp0_iter3_reg),
    .ArrayIdx_read(p_Result_1_i_reg_1916_pp0_iter3_reg),
    .ap_return_0(grp_hscale_polyphase_fu_700_ap_return_0),
    .ap_return_1(grp_hscale_polyphase_fu_700_ap_return_1),
    .ap_return_2(grp_hscale_polyphase_fu_700_ap_return_2)
);

bd_d92b_hsc_0_reg_ap_uint_9_s grp_reg_ap_uint_9_s_fu_873(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .in_V(arrPhasesH_V_q0),
    .ap_return(grp_reg_ap_uint_9_s_fu_873_ap_return),
    .ap_ce(grp_reg_ap_uint_9_s_fu_873_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln592_fu_834_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((icmp_ln608_fu_845_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln592_fu_834_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end else if (((icmp_ln592_fu_834_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp0_iter14 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state10)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_hscale_polyphase_fu_700_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_predicate_op307_call_state12_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_hscale_polyphase_fu_700_ap_start_reg <= 1'b1;
        end else if ((grp_hscale_polyphase_fu_700_ap_ready == 1'b1)) begin
            grp_hscale_polyphase_fu_700_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln608_reg_1818_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ReadEn_0_i_reg_654 <= ReadEn_1_i_reg_676;
    end else if (((icmp_ln592_fu_834_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        ReadEn_0_i_reg_654 <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln665_reg_1827_pp0_iter1_reg == 1'd0) & (icmp_ln608_reg_1818_pp0_iter1_reg == 1'd0))) begin
            ReadEn_1_i_reg_676 <= ap_phi_mux_ReadEn_0_i_phi_fu_658_p4;
        end else if (((icmp_ln665_reg_1827_pp0_iter1_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter1_reg == 1'd0))) begin
            ReadEn_1_i_reg_676 <= ReadEn_fu_953_p1;
        end else if ((1'b1 == 1'b1)) begin
            ReadEn_1_i_reg_676 <= ap_phi_reg_pp0_iter2_ReadEn_1_i_reg_676;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln583_fu_804_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_0_i_reg_609 <= i_reg_1525;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_0_i_reg_609 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j_0_i_reg_620 <= j_reg_1795;
    end else if (((icmp_ln580_fu_760_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j_0_i_reg_620 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln608_reg_1818_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        xReadPos_0_i_reg_665 <= xReadPos_2_i_reg_688;
    end else if (((icmp_ln592_fu_834_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        xReadPos_0_i_reg_665 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln665_reg_1827_pp0_iter1_reg == 1'd0) & (icmp_ln608_reg_1818_pp0_iter1_reg == 1'd0))) begin
            xReadPos_2_i_reg_688 <= ap_phi_mux_xReadPos_0_i_phi_fu_669_p4;
        end else if (((icmp_ln665_reg_1827_pp0_iter1_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter1_reg == 1'd0))) begin
            xReadPos_2_i_reg_688 <= select_ln698_fu_964_p3;
        end else if ((1'b1 == 1'b1)) begin
            xReadPos_2_i_reg_688 <= ap_phi_reg_pp0_iter2_xReadPos_2_i_reg_688;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln608_reg_1818 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_0_i_reg_642 <= x_reg_1822;
    end else if (((icmp_ln592_fu_834_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        x_0_i_reg_642 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        y_0_i_reg_631 <= y_reg_1813;
    end else if (((icmp_ln580_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        y_0_i_reg_631 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln580_fu_760_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        FiltCoeff_0_0_addr_reg_1535 <= zext_ln586_fu_772_p1;
        FiltCoeff_1_0_addr_reg_1540 <= zext_ln586_fu_772_p1;
        FiltCoeff_2_0_addr_reg_1545 <= zext_ln586_fu_772_p1;
        FiltCoeff_3_0_addr_reg_1550 <= zext_ln586_fu_772_p1;
        FiltCoeff_4_0_addr_reg_1555 <= zext_ln586_fu_772_p1;
        FiltCoeff_5_0_addr_reg_1560 <= zext_ln586_fu_772_p1;
        FiltCoeff_6_0_addr_reg_1565 <= zext_ln586_fu_772_p1;
        FiltCoeff_7_0_addr_reg_1570 <= zext_ln586_fu_772_p1;
        zext_ln586_1_reg_1530[9 : 3] <= zext_ln586_1_fu_792_p1[9 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read_reg_1494 <= Height_dout;
        InPixels_read_reg_1499 <= InPixels_dout;
        OutPixels_read_reg_1506 <= OutPixels_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LoopSize_reg_1517 <= LoopSize_fu_754_p2;
        TotalPixels_reg_1512 <= TotalPixels_fu_748_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln619_reg_1875 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        PixArray_0_val_0_V_1_fu_310 <= PixArray_0_val_0_V_fu_1056_p3;
        PixArray_0_val_1_V_1_fu_314 <= PixArray_0_val_1_V_fu_1062_p3;
        PixArray_0_val_2_V_1_fu_318 <= PixArray_0_val_2_V_fu_1068_p3;
        PixArray_1_val_0_V_1_fu_322 <= PixArray_1_val_0_V_fu_1074_p3;
        PixArray_1_val_1_V_1_fu_326 <= PixArray_1_val_1_V_fu_1080_p3;
        PixArray_1_val_2_V_1_fu_330 <= PixArray_1_val_2_V_fu_1086_p3;
        PixArray_2_val_0_V_1_fu_334 <= PixArray_2_val_0_V_fu_1092_p3;
        PixArray_2_val_1_V_1_fu_338 <= PixArray_2_val_1_V_fu_1098_p3;
        PixArray_2_val_2_V_1_fu_342 <= PixArray_2_val_2_V_fu_1104_p3;
        PixArray_3_val_0_V_1_fu_346 <= PixArray_3_val_0_V_fu_1110_p3;
        PixArray_3_val_1_V_1_fu_350 <= PixArray_3_val_1_V_fu_1116_p3;
        PixArray_3_val_2_V_1_fu_354 <= PixArray_3_val_2_V_fu_1122_p3;
        PixArray_4_val_0_V_1_fu_358 <= PixArray_4_val_0_V_fu_1128_p3;
        PixArray_4_val_1_V_1_fu_362 <= PixArray_4_val_1_V_fu_1134_p3;
        PixArray_4_val_2_V_1_fu_366 <= PixArray_4_val_2_V_fu_1140_p3;
        PixArray_5_val_0_V_1_fu_370 <= PixArray_5_val_0_V_fu_1146_p3;
        PixArray_5_val_1_V_1_fu_374 <= PixArray_5_val_1_V_fu_1152_p3;
        PixArray_5_val_2_V_1_fu_378 <= PixArray_5_val_2_V_fu_1158_p3;
        PixArray_6_val_0_V_1_fu_382 <= PixArray_6_val_0_V_fu_1164_p3;
        PixArray_6_val_1_V_1_fu_386 <= PixArray_6_val_1_V_fu_1170_p3;
        PixArray_6_val_2_V_1_fu_390 <= PixArray_6_val_2_V_fu_1176_p3;
        PixArray_7_val_0_V_1_fu_394 <= PixArray_7_val_0_V_fu_1182_p3;
        PixArray_7_val_1_V_1_fu_398 <= PixArray_7_val_1_V_fu_1188_p3;
        PixArray_7_val_2_V_1_fu_402 <= PixArray_7_val_2_V_fu_1194_p3;
        PixArray_8_val_0_V_fu_406 <= PixArray_8_val_0_V_2_reg_1836;
        PixArray_8_val_1_V_fu_410 <= PixArray_8_val_1_V_2_reg_1849;
        PixArray_8_val_2_V_fu_414 <= PixArray_8_val_2_V_2_reg_1862;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        PixArray_8_val_0_V_1_fu_418 <= SrcImg_V_val_0_V_dout;
        PixArray_8_val_1_V_1_fu_422 <= SrcImg_V_val_1_V_dout;
        PixArray_8_val_2_V_1_fu_426 <= SrcImg_V_val_2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        PixArray_8_val_0_V_2_reg_1836 <= ap_sig_allocacmp_PixArray_8_val_0_V_2;
        PixArray_8_val_1_V_2_reg_1849 <= ap_sig_allocacmp_PixArray_8_val_1_V_2;
        PixArray_8_val_2_V_2_reg_1862 <= ap_sig_allocacmp_PixArray_8_val_2_V_2;
        and_ln705_reg_1921_pp0_iter10_reg <= and_ln705_reg_1921_pp0_iter9_reg;
        and_ln705_reg_1921_pp0_iter11_reg <= and_ln705_reg_1921_pp0_iter10_reg;
        and_ln705_reg_1921_pp0_iter12_reg <= and_ln705_reg_1921_pp0_iter11_reg;
        and_ln705_reg_1921_pp0_iter13_reg <= and_ln705_reg_1921_pp0_iter12_reg;
        and_ln705_reg_1921_pp0_iter3_reg <= and_ln705_reg_1921;
        and_ln705_reg_1921_pp0_iter4_reg <= and_ln705_reg_1921_pp0_iter3_reg;
        and_ln705_reg_1921_pp0_iter5_reg <= and_ln705_reg_1921_pp0_iter4_reg;
        and_ln705_reg_1921_pp0_iter6_reg <= and_ln705_reg_1921_pp0_iter5_reg;
        and_ln705_reg_1921_pp0_iter7_reg <= and_ln705_reg_1921_pp0_iter6_reg;
        and_ln705_reg_1921_pp0_iter8_reg <= and_ln705_reg_1921_pp0_iter7_reg;
        and_ln705_reg_1921_pp0_iter9_reg <= and_ln705_reg_1921_pp0_iter8_reg;
        icmp_ln608_reg_1818_pp0_iter10_reg <= icmp_ln608_reg_1818_pp0_iter9_reg;
        icmp_ln608_reg_1818_pp0_iter11_reg <= icmp_ln608_reg_1818_pp0_iter10_reg;
        icmp_ln608_reg_1818_pp0_iter2_reg <= icmp_ln608_reg_1818_pp0_iter1_reg;
        icmp_ln608_reg_1818_pp0_iter3_reg <= icmp_ln608_reg_1818_pp0_iter2_reg;
        icmp_ln608_reg_1818_pp0_iter4_reg <= icmp_ln608_reg_1818_pp0_iter3_reg;
        icmp_ln608_reg_1818_pp0_iter5_reg <= icmp_ln608_reg_1818_pp0_iter4_reg;
        icmp_ln608_reg_1818_pp0_iter6_reg <= icmp_ln608_reg_1818_pp0_iter5_reg;
        icmp_ln608_reg_1818_pp0_iter7_reg <= icmp_ln608_reg_1818_pp0_iter6_reg;
        icmp_ln608_reg_1818_pp0_iter8_reg <= icmp_ln608_reg_1818_pp0_iter7_reg;
        icmp_ln608_reg_1818_pp0_iter9_reg <= icmp_ln608_reg_1818_pp0_iter8_reg;
        icmp_ln665_reg_1827_pp0_iter10_reg <= icmp_ln665_reg_1827_pp0_iter9_reg;
        icmp_ln665_reg_1827_pp0_iter11_reg <= icmp_ln665_reg_1827_pp0_iter10_reg;
        icmp_ln665_reg_1827_pp0_iter12_reg <= icmp_ln665_reg_1827_pp0_iter11_reg;
        icmp_ln665_reg_1827_pp0_iter13_reg <= icmp_ln665_reg_1827_pp0_iter12_reg;
        icmp_ln665_reg_1827_pp0_iter2_reg <= icmp_ln665_reg_1827_pp0_iter1_reg;
        icmp_ln665_reg_1827_pp0_iter3_reg <= icmp_ln665_reg_1827_pp0_iter2_reg;
        icmp_ln665_reg_1827_pp0_iter4_reg <= icmp_ln665_reg_1827_pp0_iter3_reg;
        icmp_ln665_reg_1827_pp0_iter5_reg <= icmp_ln665_reg_1827_pp0_iter4_reg;
        icmp_ln665_reg_1827_pp0_iter6_reg <= icmp_ln665_reg_1827_pp0_iter5_reg;
        icmp_ln665_reg_1827_pp0_iter7_reg <= icmp_ln665_reg_1827_pp0_iter6_reg;
        icmp_ln665_reg_1827_pp0_iter8_reg <= icmp_ln665_reg_1827_pp0_iter7_reg;
        icmp_ln665_reg_1827_pp0_iter9_reg <= icmp_ln665_reg_1827_pp0_iter8_reg;
        p_Result_1_i_reg_1916_pp0_iter3_reg <= p_Result_1_i_reg_1916;
        trunc_ln681_reg_1911_pp0_iter3_reg <= trunc_ln681_reg_1911;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln580_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        add_ln592_reg_1782 <= add_ln592_fu_796_p2;
        zext_ln628_reg_1787[15 : 0] <= zext_ln628_fu_801_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln665_reg_1827_pp0_iter1_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln705_reg_1921 <= and_ln705_fu_978_p2;
        p_Result_1_i_reg_1916 <= {{grp_reg_ap_uint_9_s_fu_873_ap_return[7:6]}};
        trunc_ln681_reg_1911 <= trunc_ln681_fu_925_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_1525 <= i_fu_766_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln608_reg_1818 <= icmp_ln608_fu_845_p2;
        icmp_ln608_reg_1818_pp0_iter1_reg <= icmp_ln608_reg_1818;
        icmp_ln665_reg_1827_pp0_iter1_reg <= icmp_ln665_reg_1827;
        x_0_i_reg_642_pp0_iter1_reg <= x_0_i_reg_642;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln608_reg_1818_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln619_reg_1875 <= icmp_ln619_fu_888_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln619_fu_888_p2 == 1'd0) & (icmp_ln608_reg_1818_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln625_reg_1879 <= icmp_ln625_fu_904_p2;
        icmp_ln628_reg_1907 <= icmp_ln628_fu_920_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln608_fu_845_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln665_reg_1827 <= icmp_ln665_fu_856_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        j_reg_1795 <= j_fu_810_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln583_fu_804_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        trunc_ln586_reg_1805 <= trunc_ln586_fu_830_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_reg_1822 <= x_fu_850_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        y_reg_1813 <= y_fu_839_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_0_0_address0 = FiltCoeff_0_0_addr_reg_1535;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op308_call_state13 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op307_call_state12 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        FiltCoeff_0_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_0_address0;
    end else begin
        FiltCoeff_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_0_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op308_call_state13 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op307_call_state12 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        FiltCoeff_0_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_0_ce0;
    end else begin
        FiltCoeff_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_0_0_we0 = 1'b1;
    end else begin
        FiltCoeff_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_1_0_address0 = FiltCoeff_1_0_addr_reg_1540;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op309_call_state14 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op308_call_state13 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        FiltCoeff_1_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_1_address0;
    end else begin
        FiltCoeff_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_1_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op309_call_state14 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op308_call_state13 == 1'b1) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        FiltCoeff_1_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_1_ce0;
    end else begin
        FiltCoeff_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_1_0_we0 = 1'b1;
    end else begin
        FiltCoeff_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_2_0_address0 = FiltCoeff_2_0_addr_reg_1545;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op310_call_state15 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op309_call_state14 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        FiltCoeff_2_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_2_address0;
    end else begin
        FiltCoeff_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_2_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op310_call_state15 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op309_call_state14 == 1'b1) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        FiltCoeff_2_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_2_ce0;
    end else begin
        FiltCoeff_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd2) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_2_0_we0 = 1'b1;
    end else begin
        FiltCoeff_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_3_0_address0 = FiltCoeff_3_0_addr_reg_1550;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op311_call_state16 == 1'b1) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op310_call_state15 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1)))) begin
        FiltCoeff_3_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_3_address0;
    end else begin
        FiltCoeff_3_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_3_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op311_call_state16 == 1'b1) & (ap_enable_reg_pp0_iter8 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op310_call_state15 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1)))) begin
        FiltCoeff_3_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_3_ce0;
    end else begin
        FiltCoeff_3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd3) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_3_0_we0 = 1'b1;
    end else begin
        FiltCoeff_3_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_4_0_address0 = FiltCoeff_4_0_addr_reg_1555;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op312_call_state17 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op311_call_state16 == 1'b1) & (ap_enable_reg_pp0_iter8 == 1'b1)))) begin
        FiltCoeff_4_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_4_address0;
    end else begin
        FiltCoeff_4_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_4_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op312_call_state17 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op311_call_state16 == 1'b1) & (ap_enable_reg_pp0_iter8 == 1'b1)))) begin
        FiltCoeff_4_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_4_ce0;
    end else begin
        FiltCoeff_4_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd4) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_4_0_we0 = 1'b1;
    end else begin
        FiltCoeff_4_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_5_0_address0 = FiltCoeff_5_0_addr_reg_1560;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op313_call_state18 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op312_call_state17 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b1)))) begin
        FiltCoeff_5_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_5_address0;
    end else begin
        FiltCoeff_5_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_5_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op313_call_state18 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op312_call_state17 == 1'b1) & (ap_enable_reg_pp0_iter9 == 1'b1)))) begin
        FiltCoeff_5_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_5_ce0;
    end else begin
        FiltCoeff_5_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd5) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_5_0_we0 = 1'b1;
    end else begin
        FiltCoeff_5_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_6_0_address0 = FiltCoeff_6_0_addr_reg_1565;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op314_call_state19 == 1'b1) & (ap_enable_reg_pp0_iter11 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op313_call_state18 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1)))) begin
        FiltCoeff_6_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_6_address0;
    end else begin
        FiltCoeff_6_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_6_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op314_call_state19 == 1'b1) & (ap_enable_reg_pp0_iter11 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op313_call_state18 == 1'b1) & (ap_enable_reg_pp0_iter10 == 1'b1)))) begin
        FiltCoeff_6_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_6_ce0;
    end else begin
        FiltCoeff_6_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd6) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_6_0_we0 = 1'b1;
    end else begin
        FiltCoeff_6_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_7_0_address0 = FiltCoeff_7_0_addr_reg_1570;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op315_call_state20 == 1'b1) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op314_call_state19 == 1'b1) & (ap_enable_reg_pp0_iter11 == 1'b1)))) begin
        FiltCoeff_7_0_address0 = grp_hscale_polyphase_fu_700_FiltCoeff_7_address0;
    end else begin
        FiltCoeff_7_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FiltCoeff_7_0_ce0 = 1'b1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op315_call_state20 == 1'b1) & (ap_enable_reg_pp0_iter12 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op314_call_state19 == 1'b1) & (ap_enable_reg_pp0_iter11 == 1'b1)))) begin
        FiltCoeff_7_0_ce0 = grp_hscale_polyphase_fu_700_FiltCoeff_7_ce0;
    end else begin
        FiltCoeff_7_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln586_reg_1805 == 3'd7) & (1'b1 == ap_CS_fsm_state5))) begin
        FiltCoeff_7_0_we0 = 1'b1;
    end else begin
        FiltCoeff_7_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_out_blk_n = Height_out_full_n;
    end else begin
        Height_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_out_write = 1'b1;
    end else begin
        Height_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        InPixels_blk_n = InPixels_empty_n;
    end else begin
        InPixels_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        InPixels_read = 1'b1;
    end else begin
        InPixels_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln705_reg_1921_pp0_iter13_reg) & (icmp_ln665_reg_1827_pp0_iter13_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        OutImg_V_val_0_V_blk_n = OutImg_V_val_0_V_full_n;
    end else begin
        OutImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        OutImg_V_val_0_V_write = 1'b1;
    end else begin
        OutImg_V_val_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln705_reg_1921_pp0_iter13_reg) & (icmp_ln665_reg_1827_pp0_iter13_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        OutImg_V_val_1_V_blk_n = OutImg_V_val_1_V_full_n;
    end else begin
        OutImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        OutImg_V_val_1_V_write = 1'b1;
    end else begin
        OutImg_V_val_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln705_reg_1921_pp0_iter13_reg) & (icmp_ln665_reg_1827_pp0_iter13_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        OutImg_V_val_2_V_blk_n = OutImg_V_val_2_V_full_n;
    end else begin
        OutImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        OutImg_V_val_2_V_write = 1'b1;
    end else begin
        OutImg_V_val_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        OutPixels_blk_n = OutPixels_empty_n;
    end else begin
        OutPixels_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        OutPixels_out_blk_n = OutPixels_out_full_n;
    end else begin
        OutPixels_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        OutPixels_out_write = 1'b1;
    end else begin
        OutPixels_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        OutPixels_read = 1'b1;
    end else begin
        OutPixels_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        SrcImg_V_val_0_V_blk_n = SrcImg_V_val_0_V_empty_n;
    end else begin
        SrcImg_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        SrcImg_V_val_0_V_read = 1'b1;
    end else begin
        SrcImg_V_val_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        SrcImg_V_val_1_V_blk_n = SrcImg_V_val_1_V_empty_n;
    end else begin
        SrcImg_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        SrcImg_V_val_1_V_read = 1'b1;
    end else begin
        SrcImg_V_val_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        SrcImg_V_val_2_V_blk_n = SrcImg_V_val_2_V_empty_n;
    end else begin
        SrcImg_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        SrcImg_V_val_2_V_read = 1'b1;
    end else begin
        SrcImg_V_val_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state10 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state10 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln592_fu_834_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln608_reg_1818_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_ReadEn_0_i_phi_fu_658_p4 = ReadEn_1_i_reg_676;
    end else begin
        ap_phi_mux_ReadEn_0_i_phi_fu_658_p4 = ReadEn_0_i_reg_654;
    end
end

always @ (*) begin
    if (((icmp_ln608_reg_1818_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_mux_xReadPos_0_i_phi_fu_669_p4 = xReadPos_2_i_reg_688;
    end else begin
        ap_phi_mux_xReadPos_0_i_phi_fu_669_p4 = xReadPos_0_i_reg_665;
    end
end

always @ (*) begin
    if (((icmp_ln608_reg_1818 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_x_0_i_phi_fu_646_p4 = x_reg_1822;
    end else begin
        ap_phi_mux_x_0_i_phi_fu_646_p4 = x_0_i_reg_642;
    end
end

always @ (*) begin
    if (((icmp_ln592_fu_834_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_PixArray_8_val_0_V_2 = SrcImg_V_val_0_V_dout;
    end else begin
        ap_sig_allocacmp_PixArray_8_val_0_V_2 = PixArray_8_val_0_V_1_fu_418;
    end
end

always @ (*) begin
    if (((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_PixArray_8_val_1_V_2 = SrcImg_V_val_1_V_dout;
    end else begin
        ap_sig_allocacmp_PixArray_8_val_1_V_2 = PixArray_8_val_1_V_1_fu_422;
    end
end

always @ (*) begin
    if (((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_PixArray_8_val_2_V_2 = SrcImg_V_val_2_V_dout;
    end else begin
        ap_sig_allocacmp_PixArray_8_val_2_V_2 = PixArray_8_val_2_V_1_fu_426;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        arrPhasesH_V_ce0 = 1'b1;
    end else begin
        arrPhasesH_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp307) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_hscale_polyphase_fu_700_ap_ce = 1'b1;
    end else begin
        grp_hscale_polyphase_fu_700_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp158) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_reg_ap_uint_9_s_fu_873_ap_ce = 1'b1;
    end else begin
        grp_reg_ap_uint_9_s_fu_873_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hfltCoeff_ce0 = 1'b1;
    end else begin
        hfltCoeff_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln580_fu_760_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln583_fu_804_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln592_fu_834_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter13 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter13 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Height_out_din = Height_dout;

assign LoopSize_fu_754_p2 = (TotalPixels_fu_748_p3 + 16'd5);

assign OutImg_V_val_0_V_din = grp_hscale_polyphase_fu_700_ap_return_0;

assign OutImg_V_val_1_V_din = grp_hscale_polyphase_fu_700_ap_return_1;

assign OutImg_V_val_2_V_din = grp_hscale_polyphase_fu_700_ap_return_2;

assign OutPixels_out_din = OutPixels_dout;

assign PixArray_0_val_0_V_fu_1056_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_1_val_0_V_1_fu_322);

assign PixArray_0_val_1_V_fu_1062_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_1_val_1_V_1_fu_326);

assign PixArray_0_val_2_V_fu_1068_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_1_val_2_V_1_fu_330);

assign PixArray_1_val_0_V_fu_1074_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_2_val_0_V_1_fu_334);

assign PixArray_1_val_1_V_fu_1080_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_2_val_1_V_1_fu_338);

assign PixArray_1_val_2_V_fu_1086_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_2_val_2_V_1_fu_342);

assign PixArray_2_val_0_V_fu_1092_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_3_val_0_V_1_fu_346);

assign PixArray_2_val_1_V_fu_1098_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_3_val_1_V_1_fu_350);

assign PixArray_2_val_2_V_fu_1104_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_3_val_2_V_1_fu_354);

assign PixArray_3_val_0_V_fu_1110_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_4_val_0_V_1_fu_358);

assign PixArray_3_val_1_V_fu_1116_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_4_val_1_V_1_fu_362);

assign PixArray_3_val_2_V_fu_1122_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_4_val_2_V_1_fu_366);

assign PixArray_4_val_0_V_fu_1128_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_5_val_0_V_1_fu_370);

assign PixArray_4_val_1_V_fu_1134_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_5_val_1_V_1_fu_374);

assign PixArray_4_val_2_V_fu_1140_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_5_val_2_V_1_fu_378);

assign PixArray_5_val_0_V_fu_1146_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_6_val_0_V_1_fu_382);

assign PixArray_5_val_1_V_fu_1152_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_6_val_1_V_1_fu_386);

assign PixArray_5_val_2_V_fu_1158_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_6_val_2_V_1_fu_390);

assign PixArray_6_val_0_V_fu_1164_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_7_val_0_V_1_fu_394);

assign PixArray_6_val_1_V_fu_1170_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_7_val_1_V_1_fu_398);

assign PixArray_6_val_2_V_fu_1176_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_7_val_2_V_1_fu_402);

assign PixArray_7_val_0_V_fu_1182_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_0_V_2_reg_1836 : PixArray_8_val_0_V_fu_406);

assign PixArray_7_val_1_V_fu_1188_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_1_V_2_reg_1849 : PixArray_8_val_1_V_fu_410);

assign PixArray_7_val_2_V_fu_1194_p3 = ((icmp_ln625_reg_1879[0:0] === 1'b1) ? PixArray_8_val_2_V_2_reg_1862 : PixArray_8_val_2_V_fu_414);

assign ReadEn_fu_953_p1 = icmp_ln685_fu_947_p2;

assign TotalPixels_fu_748_p3 = ((icmp_ln214_fu_744_p2[0:0] === 1'b1) ? InPixels_read_reg_1499 : OutPixels_read_reg_1506);

assign add_ln586_fu_820_p2 = (zext_ln586_1_reg_1530 + zext_ln586_2_fu_816_p1);

assign add_ln592_fu_796_p2 = (TotalPixels_reg_1512 + 16'd6);

assign add_ln628_fu_914_p2 = (zext_ln628_1_fu_910_p1 + 17'd5);

assign and_ln705_fu_978_p2 = (p_Result_2_i_fu_939_p3 & icmp_ln705_fu_973_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp158 = (((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp307 = (((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1) & (ap_enable_reg_pp0_iter14 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == OutPixels_out_full_n) | (1'b0 == Height_out_full_n) | (1'b0 == OutPixels_empty_n) | (1'b0 == InPixels_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter2_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter2_ignore_call40 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter3 = ((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter3_ignore_call34 = ((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1));
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter3_ignore_call40 = ((io_acc_block_signal_op269 == 1'b0) & (ap_predicate_op269_read_state11 == 1'b1));
end

assign ap_block_state12_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter4_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter4_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter5_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter5_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter6_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter6_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter8_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter8_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter9_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter9_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter10_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter10_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter11_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter11_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter12_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter12_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter13_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter13_ignore_call40 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22_pp0_stage0_iter14 = ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1));
end

always @ (*) begin
    ap_block_state22_pp0_stage0_iter14_ignore_call34 = ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1));
end

always @ (*) begin
    ap_block_state22_pp0_stage0_iter14_ignore_call40 = ((io_acc_block_signal_op321 == 1'b0) & (ap_predicate_op321_write_state22 == 1'b1));
end

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter0_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter0_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1_ignore_call34 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1_ignore_call40 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter2_ReadEn_1_i_reg_676 = 'bx;

assign ap_phi_reg_pp0_iter2_xReadPos_2_i_reg_688 = 'bx;

always @ (*) begin
    ap_predicate_op158_call_state9 = ((icmp_ln665_reg_1827 == 1'd1) & (icmp_ln608_reg_1818 == 1'd0));
end

always @ (*) begin
    ap_predicate_op269_read_state11 = ((icmp_ln628_reg_1907 == 1'd1) & (icmp_ln619_reg_1875 == 1'd0));
end

always @ (*) begin
    ap_predicate_op307_call_state12 = ((icmp_ln665_reg_1827_pp0_iter3_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op307_call_state12_state11 = ((icmp_ln665_reg_1827_pp0_iter2_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op308_call_state13 = ((icmp_ln665_reg_1827_pp0_iter4_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op309_call_state14 = ((icmp_ln665_reg_1827_pp0_iter5_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op310_call_state15 = ((icmp_ln665_reg_1827_pp0_iter6_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter6_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op311_call_state16 = ((icmp_ln665_reg_1827_pp0_iter7_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter7_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op312_call_state17 = ((icmp_ln665_reg_1827_pp0_iter8_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter8_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op313_call_state18 = ((icmp_ln665_reg_1827_pp0_iter9_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter9_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op314_call_state19 = ((icmp_ln665_reg_1827_pp0_iter10_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter10_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op315_call_state20 = ((icmp_ln665_reg_1827_pp0_iter11_reg == 1'd1) & (icmp_ln608_reg_1818_pp0_iter11_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op321_write_state22 = ((1'd1 == and_ln705_reg_1921_pp0_iter13_reg) & (icmp_ln665_reg_1827_pp0_iter13_reg == 1'd1));
end

assign arrPhasesH_V_address0 = zext_ln672_fu_868_p1;

assign grp_hscale_polyphase_fu_700_ap_start = grp_hscale_polyphase_fu_700_ap_start_reg;

assign hfltCoeff_address0 = zext_ln586_3_fu_825_p1;

assign i_fu_766_p2 = (i_0_i_reg_609 + 7'd1);

assign icmp_ln214_fu_744_p2 = ((OutPixels_read_reg_1506 < InPixels_read_reg_1499) ? 1'b1 : 1'b0);

assign icmp_ln580_fu_760_p2 = ((i_0_i_reg_609 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln583_fu_804_p2 = ((j_0_i_reg_620 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln592_fu_834_p2 = ((y_0_i_reg_631 == Height_read_reg_1494) ? 1'b1 : 1'b0);

assign icmp_ln608_fu_845_p2 = ((ap_phi_mux_x_0_i_phi_fu_646_p4 == add_ln592_reg_1782) ? 1'b1 : 1'b0);

assign icmp_ln619_fu_888_p2 = ((ap_phi_mux_ReadEn_0_i_phi_fu_658_p4 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln625_fu_904_p2 = ((tmp_9_fu_894_p4 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln628_fu_920_p2 = ((add_ln628_fu_914_p2 < zext_ln628_reg_1787) ? 1'b1 : 1'b0);

assign icmp_ln665_fu_856_p2 = ((ap_phi_mux_x_0_i_phi_fu_646_p4 > 16'd4) ? 1'b1 : 1'b0);

assign icmp_ln685_fu_947_p2 = ((p_Result_1_i_fu_929_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln705_fu_973_p2 = ((x_0_i_reg_642_pp0_iter1_reg < LoopSize_reg_1517) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op269 = (SrcImg_V_val_2_V_empty_n & SrcImg_V_val_1_V_empty_n & SrcImg_V_val_0_V_empty_n);

assign io_acc_block_signal_op321 = (OutImg_V_val_2_V_full_n & OutImg_V_val_1_V_full_n & OutImg_V_val_0_V_full_n);

assign j_fu_810_p2 = (j_0_i_reg_620 + 4'd1);

assign p_Result_1_i_fu_929_p4 = {{grp_reg_ap_uint_9_s_fu_873_ap_return[7:6]}};

assign p_Result_2_i_fu_939_p3 = grp_reg_ap_uint_9_s_fu_873_ap_return[9'd8];

assign select_ln698_fu_964_p3 = ((icmp_ln685_fu_947_p2[0:0] === 1'b1) ? xReadPos_fu_958_p2 : ap_phi_mux_xReadPos_0_i_phi_fu_669_p4);

assign tmp_9_fu_894_p4 = {{x_0_i_reg_642_pp0_iter1_reg[15:1]}};

assign tmp_fu_784_p3 = {{i_0_i_reg_609}, {3'd0}};

assign trunc_ln586_fu_830_p1 = j_0_i_reg_620[2:0];

assign trunc_ln681_fu_925_p1 = grp_reg_ap_uint_9_s_fu_873_ap_return[5:0];

assign xReadPos_fu_958_p2 = (16'd1 + ap_phi_mux_xReadPos_0_i_phi_fu_669_p4);

assign x_fu_850_p2 = (ap_phi_mux_x_0_i_phi_fu_646_p4 + 16'd1);

assign xbySamples_fu_862_p2 = ($signed(16'd65531) + $signed(ap_phi_mux_x_0_i_phi_fu_646_p4));

assign y_fu_839_p2 = (y_0_i_reg_631 + 16'd1);

assign zext_ln586_1_fu_792_p1 = tmp_fu_784_p3;

assign zext_ln586_2_fu_816_p1 = j_0_i_reg_620;

assign zext_ln586_3_fu_825_p1 = add_ln586_fu_820_p2;

assign zext_ln586_fu_772_p1 = i_0_i_reg_609;

assign zext_ln628_1_fu_910_p1 = ap_phi_mux_xReadPos_0_i_phi_fu_669_p4;

assign zext_ln628_fu_801_p1 = InPixels_read_reg_1499;

assign zext_ln672_fu_868_p1 = xbySamples_fu_862_p2;

always @ (posedge ap_clk) begin
    zext_ln586_1_reg_1530[2:0] <= 3'b000;
    zext_ln586_1_reg_1530[10] <= 1'b0;
    zext_ln628_reg_1787[16] <= 1'b0;
end

endmodule //bd_d92b_hsc_0_hscale_core_polyphas
