// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgPatternColorBars (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        y,
        x,
        width,
        color,
        bck_motion_en,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] y;
input  [15:0] x;
input  [15:0] width;
input  [7:0] color;
input  [15:0] bck_motion_en;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] s;
reg   [7:0] hBarSel_3_0;
wire   [2:0] tpgBarSelRgb_r_address0;
reg    tpgBarSelRgb_r_ce0;
wire   [0:0] tpgBarSelRgb_r_q0;
wire   [2:0] tpgBarSelYuv_y_address0;
reg    tpgBarSelYuv_y_ce0;
wire   [7:0] tpgBarSelYuv_y_q0;
wire   [2:0] tpgBarSelRgb_g_address0;
reg    tpgBarSelRgb_g_ce0;
wire   [0:0] tpgBarSelRgb_g_q0;
wire   [2:0] tpgBarSelYuv_v_address0;
reg    tpgBarSelYuv_v_ce0;
wire   [7:0] tpgBarSelYuv_v_q0;
wire   [2:0] tpgBarSelYuv_u_address0;
reg    tpgBarSelYuv_u_ce0;
wire   [7:0] tpgBarSelYuv_u_q0;
wire   [2:0] tpgBarSelRgb_b_address0;
reg    tpgBarSelRgb_b_ce0;
wire   [0:0] tpgBarSelRgb_b_q0;
reg   [10:0] xBar_V_0;
reg   [31:0] count;
wire   [0:0] icmp_ln1161_fu_223_p2;
wire   [10:0] barWidth_V_fu_251_p4;
wire   [0:0] icmp_ln1172_fu_261_p2;
reg   [0:0] icmp_ln1172_reg_598;
wire   [7:0] trunc_ln1174_fu_267_p1;
reg   [7:0] trunc_ln1174_reg_602;
wire   [0:0] icmp_ln1187_fu_271_p2;
wire   [0:0] and_ln1188_1_fu_299_p2;
reg   [0:0] and_ln1188_1_reg_615;
reg   [0:0] and_ln1188_1_reg_615_pp0_iter1_reg;
wire   [0:0] icmp_ln1192_fu_305_p2;
wire   [0:0] icmp_ln1194_fu_317_p2;
reg   [0:0] icmp_ln1194_reg_624;
wire   [0:0] or_ln1198_fu_383_p2;
reg   [0:0] or_ln1198_reg_628;
wire   [31:0] select_ln1198_fu_389_p3;
reg   [31:0] select_ln1198_reg_633;
reg    ap_block_pp0_stage0_subdone;
reg   [7:0] ap_phi_mux_hBarSel_3_0_loc_0_phi_fu_189_p6;
wire   [7:0] ap_phi_reg_pp0_iter0_hBarSel_3_0_loc_0_reg_186;
reg   [7:0] ap_phi_reg_pp0_iter1_hBarSel_3_0_loc_0_reg_186;
wire   [0:0] icmp_ln887_fu_433_p2;
wire   [7:0] zext_ln1184_fu_466_p1;
reg   [0:0] ap_phi_mux_s_flag_4_phi_fu_200_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_s_flag_4_reg_197;
reg   [0:0] ap_phi_reg_pp0_iter1_s_flag_4_reg_197;
reg   [31:0] ap_phi_mux_s_new_4_phi_fu_213_p6;
wire   [31:0] ap_phi_reg_pp0_iter0_s_new_4_reg_209;
reg   [31:0] ap_phi_reg_pp0_iter1_s_new_4_reg_209;
wire   [63:0] zext_ln1187_fu_500_p1;
reg   [31:0] ap_sig_allocacmp_s_load;
wire   [10:0] add_ln214_1_fu_444_p2;
wire   [10:0] add_ln214_fu_477_p2;
wire   [31:0] select_ln1198_1_fu_397_p3;
wire   [13:0] trunc_ln1168_fu_241_p1;
wire   [13:0] add_ln1168_fu_245_p2;
wire   [31:0] select_ln1161_fu_233_p3;
wire   [0:0] trunc_ln1188_fu_277_p1;
wire   [0:0] xor_ln1187_fu_281_p2;
wire   [0:0] and_ln1188_fu_293_p2;
wire   [0:0] icmp_ln1188_fu_287_p2;
wire   [15:0] or_ln1194_fu_311_p2;
wire   [28:0] tmp_fu_333_p4;
wire   [31:0] add_ln1196_fu_327_p2;
wire   [0:0] icmp_ln1200_fu_349_p2;
wire   [31:0] add_ln1202_fu_355_p2;
wire   [0:0] icmp_ln1198_fu_343_p2;
wire   [0:0] xor_ln1198_fu_377_p2;
wire   [31:0] select_ln1200_fu_361_p3;
wire   [31:0] select_ln1200_1_fu_369_p3;
wire   [11:0] zext_ln1353_fu_423_p1;
wire   [11:0] add_ln1353_fu_427_p2;
wire   [11:0] zext_ln1187_1_fu_411_p1;
wire   [10:0] sub_ln214_fu_439_p2;
wire   [2:0] trunc_ln1184_fu_456_p1;
wire   [2:0] add_ln1184_fu_460_p2;
wire   [7:0] select_ln300_fu_516_p3;
wire   [7:0] select_ln300_3_fu_531_p3;
wire   [7:0] select_ln1187_1_fu_539_p3;
wire   [7:0] select_ln300_4_fu_553_p3;
wire   [7:0] select_ln1187_fu_524_p3;
wire   [7:0] select_ln1188_fu_546_p3;
wire   [7:0] select_ln1187_2_fu_561_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_52;
reg    ap_condition_183;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 s = 32'd0;
#0 hBarSel_3_0 = 8'd0;
#0 xBar_V_0 = 11'd0;
#0 count = 32'd0;
end

design_1_v_tpg_0_0_tpgPatternCheckerdEe #(
    .DataWidth( 1 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelRgb_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelRgb_r_address0),
    .ce0(tpgBarSelRgb_r_ce0),
    .q0(tpgBarSelRgb_r_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckereOg #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelYuv_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelYuv_y_address0),
    .ce0(tpgBarSelYuv_y_ce0),
    .q0(tpgBarSelYuv_y_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckerfYi #(
    .DataWidth( 1 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelRgb_g_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelRgb_g_address0),
    .ce0(tpgBarSelRgb_g_ce0),
    .q0(tpgBarSelRgb_g_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckerg8j #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelYuv_v_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelYuv_v_address0),
    .ce0(tpgBarSelYuv_v_ce0),
    .q0(tpgBarSelYuv_v_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckerhbi #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelYuv_u_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelYuv_u_address0),
    .ce0(tpgBarSelYuv_u_ce0),
    .q0(tpgBarSelYuv_u_q0)
);

design_1_v_tpg_0_0_tpgPatternCheckeribs #(
    .DataWidth( 1 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
tpgBarSelRgb_b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tpgBarSelRgb_b_address0),
    .ce0(tpgBarSelRgb_b_ce0),
    .q0(tpgBarSelRgb_b_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_52)) begin
        if ((icmp_ln1172_fu_261_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_hBarSel_3_0_loc_0_reg_186 <= trunc_ln1174_fu_267_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_hBarSel_3_0_loc_0_reg_186 <= ap_phi_reg_pp0_iter0_hBarSel_3_0_loc_0_reg_186;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1192_fu_305_p2 == 1'd0)) | ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1194_fu_317_p2 == 1'd0) & (icmp_ln1192_fu_305_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_s_flag_4_reg_197 <= icmp_ln1161_fu_223_p2;
    end else if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_s_flag_4_reg_197 <= ap_phi_reg_pp0_iter0_s_flag_4_reg_197;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1192_fu_305_p2 == 1'd0)) | ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1194_fu_317_p2 == 1'd0) & (icmp_ln1192_fu_305_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_s_new_4_reg_209 <= 32'd0;
    end else if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_s_new_4_reg_209 <= ap_phi_reg_pp0_iter0_s_new_4_reg_209;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((icmp_ln1172_reg_598 == 1'd1)) begin
            hBarSel_3_0 <= trunc_ln1174_reg_602;
        end else if (((icmp_ln887_fu_433_p2 == 1'd0) & (icmp_ln1172_reg_598 == 1'd0))) begin
            hBarSel_3_0 <= zext_ln1184_fu_466_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_183)) begin
        if ((icmp_ln1172_reg_598 == 1'd1)) begin
            xBar_V_0 <= 11'd0;
        end else if (((icmp_ln887_fu_433_p2 == 1'd1) & (icmp_ln1172_reg_598 == 1'd0))) begin
            xBar_V_0 <= add_ln214_fu_477_p2;
        end else if (((icmp_ln887_fu_433_p2 == 1'd0) & (icmp_ln1172_reg_598 == 1'd0))) begin
            xBar_V_0 <= add_ln214_1_fu_444_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1188_1_reg_615 <= and_ln1188_1_fu_299_p2;
        and_ln1188_1_reg_615_pp0_iter1_reg <= and_ln1188_1_reg_615;
        icmp_ln1172_reg_598 <= icmp_ln1172_fu_261_p2;
        trunc_ln1174_reg_602 <= trunc_ln1174_fu_267_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1194_fu_317_p2 == 1'd1) & (icmp_ln1192_fu_305_p2 == 1'd1))) begin
        count <= select_ln1198_1_fu_397_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1192_fu_305_p2 == 1'd1))) begin
        icmp_ln1194_reg_624 <= icmp_ln1194_fu_317_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1194_fu_317_p2 == 1'd1) & (icmp_ln1192_fu_305_p2 == 1'd1))) begin
        or_ln1198_reg_628 <= or_ln1198_fu_383_p2;
        select_ln1198_reg_633 <= select_ln1198_fu_389_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_s_flag_4_phi_fu_200_p6 == 1'd1))) begin
        s <= ap_phi_mux_s_new_4_phi_fu_213_p6;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln1172_reg_598 == 1'd0)) begin
        if ((icmp_ln887_fu_433_p2 == 1'd0)) begin
            ap_phi_mux_hBarSel_3_0_loc_0_phi_fu_189_p6 = zext_ln1184_fu_466_p1;
        end else if ((icmp_ln887_fu_433_p2 == 1'd1)) begin
            ap_phi_mux_hBarSel_3_0_loc_0_phi_fu_189_p6 = hBarSel_3_0;
        end else begin
            ap_phi_mux_hBarSel_3_0_loc_0_phi_fu_189_p6 = ap_phi_reg_pp0_iter1_hBarSel_3_0_loc_0_reg_186;
        end
    end else begin
        ap_phi_mux_hBarSel_3_0_loc_0_phi_fu_189_p6 = ap_phi_reg_pp0_iter1_hBarSel_3_0_loc_0_reg_186;
    end
end

always @ (*) begin
    if (((icmp_ln1194_reg_624 == 1'd1) & (icmp_ln1192_fu_305_p2 == 1'd1))) begin
        ap_phi_mux_s_flag_4_phi_fu_200_p6 = or_ln1198_reg_628;
    end else begin
        ap_phi_mux_s_flag_4_phi_fu_200_p6 = ap_phi_reg_pp0_iter1_s_flag_4_reg_197;
    end
end

always @ (*) begin
    if (((icmp_ln1194_reg_624 == 1'd1) & (icmp_ln1192_fu_305_p2 == 1'd1))) begin
        ap_phi_mux_s_new_4_phi_fu_213_p6 = select_ln1198_reg_633;
    end else begin
        ap_phi_mux_s_new_4_phi_fu_213_p6 = ap_phi_reg_pp0_iter1_s_new_4_reg_209;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_phi_mux_s_flag_4_phi_fu_200_p6 == 1'd1))) begin
        ap_sig_allocacmp_s_load = ap_phi_mux_s_new_4_phi_fu_213_p6;
    end else begin
        ap_sig_allocacmp_s_load = s;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelRgb_b_ce0 = 1'b1;
    end else begin
        tpgBarSelRgb_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelRgb_g_ce0 = 1'b1;
    end else begin
        tpgBarSelRgb_g_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelRgb_r_ce0 = 1'b1;
    end else begin
        tpgBarSelRgb_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelYuv_u_ce0 = 1'b1;
    end else begin
        tpgBarSelYuv_u_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelYuv_v_ce0 = 1'b1;
    end else begin
        tpgBarSelYuv_v_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tpgBarSelYuv_y_ce0 = 1'b1;
    end else begin
        tpgBarSelYuv_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1168_fu_245_p2 = (14'd7 + trunc_ln1168_fu_241_p1);

assign add_ln1184_fu_460_p2 = (3'd1 + trunc_ln1184_fu_456_p1);

assign add_ln1196_fu_327_p2 = (count + 32'd1);

assign add_ln1202_fu_355_p2 = (select_ln1161_fu_233_p3 + 32'd1);

assign add_ln1353_fu_427_p2 = (zext_ln1353_fu_423_p1 + 12'd1);

assign add_ln214_1_fu_444_p2 = (xBar_V_0 + sub_ln214_fu_439_p2);

assign add_ln214_fu_477_p2 = (xBar_V_0 + 11'd1);

assign and_ln1188_1_fu_299_p2 = (icmp_ln1188_fu_287_p2 & and_ln1188_fu_293_p2);

assign and_ln1188_fu_293_p2 = (xor_ln1187_fu_281_p2 & trunc_ln1188_fu_277_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_183 = ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_52 = ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_hBarSel_3_0_loc_0_reg_186 = 'bx;

assign ap_phi_reg_pp0_iter0_s_flag_4_reg_197 = 'bx;

assign ap_phi_reg_pp0_iter0_s_new_4_reg_209 = 'bx;

assign ap_return_0 = select_ln1187_fu_524_p3;

assign ap_return_1 = select_ln1188_fu_546_p3;

assign ap_return_2 = select_ln1187_2_fu_561_p3;

assign barWidth_V_fu_251_p4 = {{add_ln1168_fu_245_p2[13:3]}};

assign icmp_ln1161_fu_223_p2 = ((bck_motion_en == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1172_fu_261_p2 = ((x == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1187_fu_271_p2 = ((color == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1188_fu_287_p2 = ((color != 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln1192_fu_305_p2 = ((bck_motion_en == 16'd1) ? 1'b1 : 1'b0);

assign icmp_ln1194_fu_317_p2 = ((or_ln1194_fu_311_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1198_fu_343_p2 = (($signed(tmp_fu_333_p4) < $signed(29'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1200_fu_349_p2 = ((add_ln1196_fu_327_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_433_p2 = ((add_ln1353_fu_427_p2 < zext_ln1187_1_fu_411_p1) ? 1'b1 : 1'b0);

assign or_ln1194_fu_311_p2 = (y | x);

assign or_ln1198_fu_383_p2 = (xor_ln1198_fu_377_p2 | icmp_ln1200_fu_349_p2);

assign select_ln1161_fu_233_p3 = ((icmp_ln1161_fu_223_p2[0:0] === 1'b1) ? 32'd0 : ap_sig_allocacmp_s_load);

assign select_ln1187_1_fu_539_p3 = ((icmp_ln1187_fu_271_p2[0:0] === 1'b1) ? select_ln300_3_fu_531_p3 : tpgBarSelYuv_u_q0);

assign select_ln1187_2_fu_561_p3 = ((icmp_ln1187_fu_271_p2[0:0] === 1'b1) ? select_ln300_4_fu_553_p3 : tpgBarSelYuv_v_q0);

assign select_ln1187_fu_524_p3 = ((icmp_ln1187_fu_271_p2[0:0] === 1'b1) ? select_ln300_fu_516_p3 : tpgBarSelYuv_y_q0);

assign select_ln1188_fu_546_p3 = ((and_ln1188_1_reg_615_pp0_iter1_reg[0:0] === 1'b1) ? tpgBarSelYuv_v_q0 : select_ln1187_1_fu_539_p3);

assign select_ln1198_1_fu_397_p3 = ((icmp_ln1198_fu_343_p2[0:0] === 1'b1) ? select_ln1200_1_fu_369_p3 : add_ln1196_fu_327_p2);

assign select_ln1198_fu_389_p3 = ((icmp_ln1198_fu_343_p2[0:0] === 1'b1) ? select_ln1200_fu_361_p3 : 32'd0);

assign select_ln1200_1_fu_369_p3 = ((icmp_ln1200_fu_349_p2[0:0] === 1'b1) ? 32'd0 : add_ln1196_fu_327_p2);

assign select_ln1200_fu_361_p3 = ((icmp_ln1200_fu_349_p2[0:0] === 1'b1) ? add_ln1202_fu_355_p2 : 32'd0);

assign select_ln300_3_fu_531_p3 = ((tpgBarSelRgb_g_q0[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign select_ln300_4_fu_553_p3 = ((tpgBarSelRgb_b_q0[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign select_ln300_fu_516_p3 = ((tpgBarSelRgb_r_q0[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign sub_ln214_fu_439_p2 = (11'd1 - barWidth_V_fu_251_p4);

assign tmp_fu_333_p4 = {{select_ln1161_fu_233_p3[31:3]}};

assign tpgBarSelRgb_b_address0 = zext_ln1187_fu_500_p1;

assign tpgBarSelRgb_g_address0 = zext_ln1187_fu_500_p1;

assign tpgBarSelRgb_r_address0 = zext_ln1187_fu_500_p1;

assign tpgBarSelYuv_u_address0 = zext_ln1187_fu_500_p1;

assign tpgBarSelYuv_v_address0 = zext_ln1187_fu_500_p1;

assign tpgBarSelYuv_y_address0 = zext_ln1187_fu_500_p1;

assign trunc_ln1168_fu_241_p1 = width[13:0];

assign trunc_ln1174_fu_267_p1 = select_ln1161_fu_233_p3[7:0];

assign trunc_ln1184_fu_456_p1 = hBarSel_3_0[2:0];

assign trunc_ln1188_fu_277_p1 = x[0:0];

assign xor_ln1187_fu_281_p2 = (icmp_ln1187_fu_271_p2 ^ 1'd1);

assign xor_ln1198_fu_377_p2 = (icmp_ln1198_fu_343_p2 ^ 1'd1);

assign zext_ln1184_fu_466_p1 = add_ln1184_fu_460_p2;

assign zext_ln1187_1_fu_411_p1 = barWidth_V_fu_251_p4;

assign zext_ln1187_fu_500_p1 = ap_phi_mux_hBarSel_3_0_loc_0_phi_fu_189_p6;

assign zext_ln1353_fu_423_p1 = xBar_V_0;

endmodule //design_1_v_tpg_0_0_tpgPatternColorBars
