
#ifndef _V_MIX_CONFIG_H_
#define _V_MIX_CONFIG_H_

#define SAMPLES_PER_CLOCK       1
#define MAX_COLS                1920
#define MAX_ROWS                1080
#define MAX_DATA_WIDTH          8
#define NR_COMPONENTS           3
#define NR_LAYERS				2
#define NR_LAYERS_MIN_1			1
#define BITS_PER_SAMPLE         (NR_COMPONENTS*MAX_DATA_WIDTH)
#define BITS_PER_CLOCK          (BITS_PER_SAMPLE*SAMPLES_PER_CLOCK)
#define AXIMM_DATA_WIDTH		(32*SAMPLES_PER_CLOCK*2)
#define AXIMM_NUM_OUTSTANDING   4
#define AXIMM_BURST_LENGTH      16

#define LAYER1_ALPHA			true
#define LAYER2_ALPHA			false
#define LAYER3_ALPHA			false
#define LAYER4_ALPHA			false
#define LAYER5_ALPHA			false
#define LAYER6_ALPHA			false
#define LAYER7_ALPHA			false
#define LAYER8_ALPHA			false
#define LAYER9_ALPHA			false
#define LAYER10_ALPHA			false
#define LAYER11_ALPHA			false
#define LAYER12_ALPHA			false
#define LAYER13_ALPHA			false
#define LAYER14_ALPHA			false
#define LAYER15_ALPHA			false
#define LAYER16_ALPHA			false

#define LAYER1_UPSAMPLE			false
#define LAYER2_UPSAMPLE			false
#define LAYER3_UPSAMPLE			false
#define LAYER4_UPSAMPLE			false
#define LAYER5_UPSAMPLE			false
#define LAYER6_UPSAMPLE			false
#define LAYER7_UPSAMPLE			false
#define LAYER8_UPSAMPLE			false
#define LAYER9_UPSAMPLE			false
#define LAYER10_UPSAMPLE		false
#define LAYER11_UPSAMPLE		false
#define LAYER12_UPSAMPLE		false
#define LAYER13_UPSAMPLE		false
#define LAYER14_UPSAMPLE		false
#define LAYER15_UPSAMPLE		false
#define LAYER16_UPSAMPLE		false

#define LAYER1_MAX_WIDTH		1920
#define LAYER2_MAX_WIDTH		1920
#define LAYER3_MAX_WIDTH		1920
#define LAYER4_MAX_WIDTH		1920
#define LAYER5_MAX_WIDTH		1920
#define LAYER6_MAX_WIDTH		1920
#define LAYER7_MAX_WIDTH		1920
#define LAYER8_MAX_WIDTH		1920
#define LAYER9_MAX_WIDTH		1920
#define LAYER10_MAX_WIDTH		1920
#define LAYER11_MAX_WIDTH		1920
#define LAYER12_MAX_WIDTH		1920
#define LAYER13_MAX_WIDTH		1920
#define LAYER14_MAX_WIDTH		1920
#define LAYER15_MAX_WIDTH		1920
#define LAYER16_MAX_WIDTH		1920

#define OUTPUT_VIDEO_FORMAT		0
#define INPUT_VIDEO_FORMAT		OUTPUT_VIDEO_FORMAT
#define LAYER1_VIDEO_FORMAT		5
#define LAYER2_VIDEO_FORMAT		10
#define LAYER3_VIDEO_FORMAT		10
#define LAYER4_VIDEO_FORMAT		10
#define LAYER5_VIDEO_FORMAT		10
#define LAYER6_VIDEO_FORMAT		10
#define LAYER7_VIDEO_FORMAT		10
#define LAYER8_VIDEO_FORMAT		10
#define LAYER9_VIDEO_FORMAT		10
#define LAYER10_VIDEO_FORMAT		10
#define LAYER11_VIDEO_FORMAT		10
#define LAYER12_VIDEO_FORMAT		10
#define LAYER13_VIDEO_FORMAT		10
#define LAYER14_VIDEO_FORMAT		10
#define LAYER15_VIDEO_FORMAT		10
#define LAYER16_VIDEO_FORMAT		10

#define LAYER1_INTF_TYPE		1
#define LAYER2_INTF_TYPE		0
#define LAYER3_INTF_TYPE		0
#define LAYER4_INTF_TYPE		0
#define LAYER5_INTF_TYPE		0
#define LAYER6_INTF_TYPE		0
#define LAYER7_INTF_TYPE		0
#define LAYER8_INTF_TYPE		0
#define LAYER9_INTF_TYPE		0
#define LAYER10_INTF_TYPE		0
#define LAYER11_INTF_TYPE		0
#define LAYER12_INTF_TYPE		0
#define LAYER13_INTF_TYPE		0
#define LAYER14_INTF_TYPE		0
#define LAYER15_INTF_TYPE		0
#define LAYER16_INTF_TYPE		0

#define LAYER1_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER1_VIDEO_FORMAT)
#define LAYER2_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER2_VIDEO_FORMAT)
#define LAYER3_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER3_VIDEO_FORMAT)
#define LAYER4_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER4_VIDEO_FORMAT)
#define LAYER5_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER5_VIDEO_FORMAT)
#define LAYER6_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER6_VIDEO_FORMAT)
#define LAYER7_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER7_VIDEO_FORMAT)
#define LAYER8_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER8_VIDEO_FORMAT)
#define LAYER9_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER9_VIDEO_FORMAT)
#define LAYER10_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER10_VIDEO_FORMAT)
#define LAYER11_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER11_VIDEO_FORMAT)
#define LAYER12_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER12_VIDEO_FORMAT)
#define LAYER13_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER13_VIDEO_FORMAT)
#define LAYER14_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER14_VIDEO_FORMAT)
#define LAYER15_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER15_VIDEO_FORMAT)
#define LAYER16_PIXEL_ALPHA		IS_PIXEL_ALPHA(LAYER16_VIDEO_FORMAT)

#define LOGO_LAYER				false
#define MAX_LOGO_WIDTH			64
#define MAX_LOGO_HEIGHT			64
#define LOGO_TRANSPARENCY_COLOR false
#define LOGO_PIXEL_ALPHA		false

#define PLANE0_STREAM_DEPTH     240

#define USE_URAM                0

#endif
