#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 75000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 75000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 75000000

/******************************************************************/


/* Definitions for peripheral MICROBLAZE_0 */
#define XPAR_MICROBLAZE_0_ADDR_SIZE 32
#define XPAR_MICROBLAZE_0_ADDR_TAG_BITS 18
#define XPAR_MICROBLAZE_0_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_0_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_0_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_0_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_0_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_0_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_0_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_0_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_0_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_0_DADDR_SIZE 32
#define XPAR_MICROBLAZE_0_DATA_SIZE 32
#define XPAR_MICROBLAZE_0_DCACHE_ADDR_TAG 18
#define XPAR_MICROBLAZE_0_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_0_DCACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_0_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_0_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_0_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_0_DCACHE_HIGHADDR 0xFFFFFFFF
#define XPAR_MICROBLAZE_0_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_0_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_0_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_0_DC_AXI_MON 0
#define XPAR_MICROBLAZE_0_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_0_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_0_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_0_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_0_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_0_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_0_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_0_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_0_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_0_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_0_DP_AXI_MON 0
#define XPAR_MICROBLAZE_0_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_0_D_AXI 1
#define XPAR_MICROBLAZE_0_D_LMB 1
#define XPAR_MICROBLAZE_0_D_LMB_MON 0
#define XPAR_MICROBLAZE_0_D_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_0_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_0_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_0_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_0_ENDIANNESS 1
#define XPAR_MICROBLAZE_0_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_0_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_0_FREQ 75000000
#define XPAR_MICROBLAZE_0_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_0_FSL_LINKS 0
#define XPAR_MICROBLAZE_0_IADDR_SIZE 32
#define XPAR_MICROBLAZE_0_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_0_ICACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_0_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_0_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_0_ICACHE_HIGHADDR 0xFFFFFFFF
#define XPAR_MICROBLAZE_0_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_0_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_0_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_0_IC_AXI_MON 0
#define XPAR_MICROBLAZE_0_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_0_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_0_INSTR_SIZE 32
#define XPAR_MICROBLAZE_0_INTERCONNECT 2
#define XPAR_MICROBLAZE_0_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_0_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_0_IP_AXI_MON 0
#define XPAR_MICROBLAZE_0_I_AXI 0
#define XPAR_MICROBLAZE_0_I_LMB 1
#define XPAR_MICROBLAZE_0_I_LMB_MON 0
#define XPAR_MICROBLAZE_0_I_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_0_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_0_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_0_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_0_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_0_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_0_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_0_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_0_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_0_MMU_ZONES 16
#define XPAR_MICROBLAZE_0_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_0_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_0_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_0_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_0_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_0_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_0_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_0_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_0_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_0_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_0_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_0_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_0_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_0_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_0_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_0_OPTIMIZATION 0
#define XPAR_MICROBLAZE_0_PC_WIDTH 32
#define XPAR_MICROBLAZE_0_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_0_PVR 0
#define XPAR_MICROBLAZE_0_PVR_USER1 0x00
#define XPAR_MICROBLAZE_0_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_0_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_0_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_0_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_0_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_0_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_0_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_0_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_0_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_0_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_0_SCO 0
#define XPAR_MICROBLAZE_0_TRACE 0
#define XPAR_MICROBLAZE_0_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_0_USE_BARREL 0
#define XPAR_MICROBLAZE_0_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_0_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_0_USE_DCACHE 1
#define XPAR_MICROBLAZE_0_USE_DIV 0
#define XPAR_MICROBLAZE_0_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_0_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_0_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_0_USE_FPU 0
#define XPAR_MICROBLAZE_0_USE_HW_MUL 0
#define XPAR_MICROBLAZE_0_USE_ICACHE 1
#define XPAR_MICROBLAZE_0_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_0_USE_MMU 0
#define XPAR_MICROBLAZE_0_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_0_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_0_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_0_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_0_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_0_COMPONENT_NAME design_1_microblaze_0_0
#define XPAR_MICROBLAZE_0_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_0_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_0_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_0_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_MICROBLAZE_ID 0
#define XPAR_MICROBLAZE_ADDR_SIZE 32
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 18
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DADDR_SIZE 32
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 18
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0xFFFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_D_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 75000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_IADDR_SIZE 32
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 1
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x80000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0xFFFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INSTR_SIZE 32
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_I_LMB_PROTOCOL 0
#define XPAR_MICROBLAZE_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 0
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 1
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 1
#define XPAR_MICROBLAZE_USE_INTERRUPT 2
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME design_1_microblaze_0_0
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/

#define STDIN_BASEADDRESS 0x40600000
#define STDOUT_BASEADDRESS 0x40600000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_MB
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver PMODHYGRO */
#define XPAR_PMODHYGRO_NUM_INSTANCES 1

/* Definitions for peripheral PMODHYGRO_0 */
#define XPAR_PMODHYGRO_0_DEVICE_ID 0
#define XPAR_PMODHYGRO_0_AXI_LITE_IIC_BASEADDR 0x44AF0000
#define XPAR_PMODHYGRO_0_AXI_LITE_IIC_HIGHADDR 0x44AFFFFF
#define XPAR_PMODHYGRO_0_AXI_LITE_TMR_BASEADDR 0x44B00000
#define XPAR_PMODHYGRO_0_AXI_LITE_TMR_HIGHADDR 0x44B0FFFF


/******************************************************************/

/* Definitions for driver AXIVDMA */
#define XPAR_XAXIVDMA_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_VDMA_0 */
#define XPAR_AXI_VDMA_0_DEVICE_ID 0U
#define XPAR_AXI_VDMA_0_BASEADDR 0x44A10000U
#define XPAR_AXI_VDMA_0_HIGHADDR 0x44A1FFFFU
#define XPAR_AXI_VDMA_0_NUM_FSTORES 3U
#define XPAR_AXI_VDMA_0_INCLUDE_MM2S 1U
#define XPAR_AXI_VDMA_0_INCLUDE_MM2S_DRE 1U
#define XPAR_AXI_VDMA_0_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_0_INCLUDE_S2MM 1U
#define XPAR_AXI_VDMA_0_INCLUDE_S2MM_DRE 1U
#define XPAR_AXI_VDMA_0_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXI_VDMA_0_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_0_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXI_VDMA_0_MM2S_GENLOCK_MODE 3U
#define XPAR_AXI_VDMA_0_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXI_VDMA_0_S2MM_GENLOCK_MODE 2U
#define XPAR_AXI_VDMA_0_S2MM_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXI_VDMA_0_INCLUDE_SG 0U
#define XPAR_AXI_VDMA_0_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXI_VDMA_0_USE_FSYNC 1U
#define XPAR_AXI_VDMA_0_FLUSH_ON_FSYNC 1U
#define XPAR_AXI_VDMA_0_MM2S_LINEBUFFER_DEPTH 1024U
#define XPAR_AXI_VDMA_0_S2MM_LINEBUFFER_DEPTH 256U
#define XPAR_AXI_VDMA_0_INCLUDE_INTERNAL_GENLOCK 1U
#define XPAR_AXI_VDMA_0_S2MM_SOF_ENABLE 1U
#define XPAR_AXI_VDMA_0_M_AXIS_MM2S_TDATA_WIDTH 24U
#define XPAR_AXI_VDMA_0_S_AXIS_S2MM_TDATA_WIDTH 48U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_13 0U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXI_VDMA_0_ENABLE_DEBUG_ALL 0U
#define XPAR_AXI_VDMA_0_ADDR_WIDTH 32U
#define XPAR_AXI_VDMA_0_ENABLE_VERT_FLIP 0U


/******************************************************************/

/* Canonical definitions for peripheral AXI_VDMA_0 */
#define XPAR_AXIVDMA_0_DEVICE_ID XPAR_AXI_VDMA_0_DEVICE_ID
#define XPAR_AXIVDMA_0_BASEADDR 0x44A10000U
#define XPAR_AXIVDMA_0_HIGHADDR 0x44A1FFFFU
#define XPAR_AXIVDMA_0_NUM_FSTORES 3U
#define XPAR_AXIVDMA_0_INCLUDE_MM2S 1U
#define XPAR_AXIVDMA_0_INCLUDE_MM2S_DRE 1U
#define XPAR_AXIVDMA_0_M_AXI_MM2S_DATA_WIDTH 64U
#define XPAR_AXIVDMA_0_INCLUDE_S2MM 1U
#define XPAR_AXIVDMA_0_INCLUDE_S2MM_DRE 1U
#define XPAR_AXIVDMA_0_M_AXI_S2MM_DATA_WIDTH 64U
#define XPAR_AXIVDMA_0_AXI_MM2S_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_0_AXI_S2MM_ACLK_FREQ_HZ 0U
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_MODE 3U
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_MODE 2U
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_NUM_MASTERS 1U
#define XPAR_AXIVDMA_0_INCLUDE_SG 0U
#define XPAR_AXIVDMA_0_ENABLE_VIDPRMTR_READS 1U
#define XPAR_AXIVDMA_0_USE_FSYNC 1U
#define XPAR_AXIVDMA_0_FLUSH_ON_FSYNC 1U
#define XPAR_AXIVDMA_0_MM2S_LINEBUFFER_DEPTH 1024U
#define XPAR_AXIVDMA_0_S2MM_LINEBUFFER_DEPTH 256U
#define XPAR_AXIVDMA_0_INCLUDE_INTERNAL_GENLOCK 1U
#define XPAR_AXIVDMA_0_S2MM_SOF_ENABLE 1U
#define XPAR_AXIVDMA_0_M_AXIS_MM2S_TDATA_WIDTH 24U
#define XPAR_AXIVDMA_0_S_AXIS_S2MM_TDATA_WIDTH 48U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_1 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_5 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_6 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_7 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_9 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_13 0U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_14 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_15 1U
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_ALL 0U
#define XPAR_AXIVDMA_0_c_addr_width 32U
#define XPAR_AXIVDMA_0_c_enable_vert_flip 0U


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 3U

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_DEVICE_ID 0U
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 32U
#define XPAR_AXI_BRAM_CTRL_0_ECC 0U
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0xC0000000U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0xC0001FFFU
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 1U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x00003FFFU
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/* Definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 2U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x00003FFFU
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_0_WRITE_ACCESS 0U
#define XPAR_BRAM_0_BASEADDR 0xC0000000U
#define XPAR_BRAM_0_HIGHADDR 0xC0001FFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_1_DEVICE_ID XPAR_MICROBLAZE_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_1_WRITE_ACCESS 2U
#define XPAR_BRAM_1_BASEADDR 0x00000000U
#define XPAR_BRAM_1_HIGHADDR 0x00003FFFU
#define XPAR_BRAM_1_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_1_CTRL_HIGHADDR 0xFFFFFFFEU  

/* Canonical definitions for peripheral MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_2_DEVICE_ID XPAR_MICROBLAZE_0_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_2_DATA_WIDTH 32U
#define XPAR_BRAM_2_ECC 0U
#define XPAR_BRAM_2_FAULT_INJECT 0U
#define XPAR_BRAM_2_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_2_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_2_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_2_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_2_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_2_WRITE_ACCESS 2U
#define XPAR_BRAM_2_BASEADDR 0x00000000U
#define XPAR_BRAM_2_HIGHADDR 0x00003FFFU
#define XPAR_BRAM_2_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_2_CTRL_HIGHADDR 0xFFFFFFFEU  


/******************************************************************/

/* Definitions for driver CSI */
#define XPAR_XCSI_NUM_INSTANCES 1

/* Definitions for peripheral MIPI_CSI2_RX_SUBSYSTEM_0_RX */
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_DEVICE_ID 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_BASEADDR 0x00000000
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_HIGHADDR 0x0000FFFF
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_CSI_LANES 2
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_CSI_OFFLOAD_NONIMAGE 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_CSI_EN_VC_SUPPORT 1
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_CSI_FIXED_VC 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_CSI_OPT3_FIXEDLANES 1


/******************************************************************/

/* Canonical definitions for peripheral MIPI_CSI2_RX_SUBSYSTEM_0_RX */
#define XPAR_CSI_0_DEVICE_ID XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_RX_DEVICE_ID
#define XPAR_CSI_0_BASEADDR 0x00000000
#define XPAR_CSI_0_HIGHADDR 0x0000FFFF
#define XPAR_CSI_0_CSI_LANES 2
#define XPAR_CSI_0_CSI_OFFLOAD_NONIMAGE 0
#define XPAR_CSI_0_CSI_EN_VC_SUPPORT 1
#define XPAR_CSI_0_CSI_FIXED_VC 0
#define XPAR_CSI_0_CSI_OPT3_FIXEDLANES 1


/******************************************************************/

/* Definitions for driver DPHY */
#define XPAR_XDPHY_NUM_INSTANCES 2

/* Definitions for peripheral MIPI_CSI2_RX_SUBSYSTEM_0_PHY */
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_DEVICE_ID 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_BASEADDR 0x00010000
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_HIGHADDR 0x0001FFFF
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_DPHY_MODE 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_EN_REG_IF 1
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_DPHY_LANES 2
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_ESC_CLK_PERIOD 50.000
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_ESC_TIMEOUT 25600
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_HS_LINE_RATE 900
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_HS_TIMEOUT 65541
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_LPX_PERIOD 50
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_STABLE_CLK_PERIOD 5.000
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_TXPLL_CLKIN_PERIOD 8.0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_WAKEUP 1000000
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_EN_TIMEOUT_REGS 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_HS_SETTLE_NS 146


/* Definitions for peripheral MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0 */
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_DEVICE_ID 1
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_BASEADDR 0x00010000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_HIGHADDR 0x0001FFFF
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_DPHY_MODE 1
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_EN_REG_IF 1
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_DPHY_LANES 4
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_ESC_CLK_PERIOD 50.000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_ESC_TIMEOUT 25600
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_HS_LINE_RATE 1000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_HS_TIMEOUT 65541
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_LPX_PERIOD 50
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_STABLE_CLK_PERIOD 5.000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_TXPLL_CLKIN_PERIOD 8.0
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_WAKEUP 1000000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_EN_TIMEOUT_REGS 0
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_HS_SETTLE_NS 145


/******************************************************************/

/* Canonical definitions for peripheral MIPI_CSI2_RX_SUBSYSTEM_0_PHY */
#define XPAR_DPHY_0_NUM_INSTANCES 0
#define XPAR_DPHY_0_DEVICE_ID XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_PHY_DEVICE_ID
#define XPAR_DPHY_0_BASEADDR 0x00010000
#define XPAR_DPHY_0_HIGHADDR 0x0001FFFF
#define XPAR_DPHY_0_DPHY_MODE 0
#define XPAR_DPHY_0_EN_REG_IF 1
#define XPAR_DPHY_0_DPHY_LANES 2
#define XPAR_DPHY_0_ESC_CLK_PERIOD 50.000
#define XPAR_DPHY_0_ESC_TIMEOUT 25600
#define XPAR_DPHY_0_HS_LINE_RATE 900
#define XPAR_DPHY_0_HS_TIMEOUT 65541
#define XPAR_DPHY_0_LPX_PERIOD 50
#define XPAR_DPHY_0_STABLE_CLK_PERIOD 5.000
#define XPAR_DPHY_0_TXPLL_CLKIN_PERIOD 8.0
#define XPAR_DPHY_0_WAKEUP 1000000
#define XPAR_DPHY_0_EN_TIMEOUT_REGS 0
#define XPAR_DPHY_0_HS_SETTLE_NS 146

/* Canonical definitions for peripheral MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0 */
#define XPAR_DPHY_1_NUM_INSTANCES 0
#define XPAR_DPHY_1_DEVICE_ID XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DPHY_0_DEVICE_ID
#define XPAR_DPHY_1_BASEADDR 0x00010000
#define XPAR_DPHY_1_HIGHADDR 0x0001FFFF
#define XPAR_DPHY_1_DPHY_MODE 1
#define XPAR_DPHY_1_EN_REG_IF 1
#define XPAR_DPHY_1_DPHY_LANES 4
#define XPAR_DPHY_1_ESC_CLK_PERIOD 50.000
#define XPAR_DPHY_1_ESC_TIMEOUT 25600
#define XPAR_DPHY_1_HS_LINE_RATE 1000
#define XPAR_DPHY_1_HS_TIMEOUT 65541
#define XPAR_DPHY_1_LPX_PERIOD 50
#define XPAR_DPHY_1_STABLE_CLK_PERIOD 5.000
#define XPAR_DPHY_1_TXPLL_CLKIN_PERIOD 8.0
#define XPAR_DPHY_1_WAKEUP 1000000
#define XPAR_DPHY_1_EN_TIMEOUT_REGS 0
#define XPAR_DPHY_1_HS_SETTLE_NS 145


/******************************************************************/

/* Definitions for driver DSI */
#define XPAR_XDSI_NUM_INSTANCES 1

/* Definitions for peripheral MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0 */
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_DEVICE_ID 0
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_BASEADDR 0x00000000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_HIGHADDR 0x0000FFFF
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_DSI_LANES 4
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_DSI_DATATYPE 0x3E
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_DSI_BYTE_FIFO 2048
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_DSI_CRC_GEN 1
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_DSI_PIXELS 1


/******************************************************************/

/* Canonical definitions for peripheral MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0 */
#define XPAR_DSI_0_DEVICE_ID XPAR_MIPI_DSI_TX_SUBSYSTEM_0_MIPI_DSI_TX_CTRL_0_DEVICE_ID
#define XPAR_DSI_0_BASEADDR 0x00000000
#define XPAR_DSI_0_HIGHADDR 0x0000FFFF
#define XPAR_DSI_0_DSI_LANES 4
#define XPAR_DSI_0_DSI_DATATYPE 0x3E
#define XPAR_DSI_0_DSI_BYTE_FIFO 2048
#define XPAR_DSI_0_DSI_CRC_GEN 1
#define XPAR_DSI_0_DSI_PIXELS 1


/******************************************************************/

/* Definitions for driver DSITXSS */
#define XPAR_XDSITXSS_NUM_INSTANCES 1

/* Definitions for peripheral MIPI_DSI_TX_SUBSYSTEM_0 */
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DEVICE_ID 0
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_BASEADDR 0x44A40000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_HIGHADDR 0x44A5FFFF
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DSI_LANES 4
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DSI_DATATYPE 0x3E
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DSI_BYTE_FIFO 2048
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DSI_CRC_GEN 1
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DSI_PIXELS 1
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DPHY_LINERATE 1000
#define XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DPHY_EN_REG_IF 1


/******************************************************************/

/* Canonical definitions for peripheral MIPI_DSI_TX_SUBSYSTEM_0 */
#define XPAR_DSITXSS_0_DEVICE_ID XPAR_MIPI_DSI_TX_SUBSYSTEM_0_DEVICE_ID
#define XPAR_DSITXSS_0_BASEADDR 0x44A40000
#define XPAR_DSITXSS_0_HIGHADDR 0x44A5FFFF
#define XPAR_DSITXSS_0_DSI_LANES 4
#define XPAR_DSITXSS_0_DSI_DATATYPE 0x3E
#define XPAR_DSITXSS_0_DSI_BYTE_FIFO 2048
#define XPAR_DSITXSS_0_DSI_CRC_GEN 1
#define XPAR_DSITXSS_0_DSI_PIXELS 1
#define XPAR_DSITXSS_0_DPHY_LINERATE 1000
#define XPAR_DSITXSS_0_DPHY_EN_REG_IF 1


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 6

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000FFFF
#define XPAR_AXI_GPIO_0_DEVICE_ID 0
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_0_IS_DUAL 0


/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x4001FFFF
#define XPAR_AXI_GPIO_1_DEVICE_ID 1
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_1_IS_DUAL 0


/* Definitions for peripheral AXI_GPIO_2 */
#define XPAR_AXI_GPIO_2_BASEADDR 0x40020000
#define XPAR_AXI_GPIO_2_HIGHADDR 0x4002FFFF
#define XPAR_AXI_GPIO_2_DEVICE_ID 2
#define XPAR_AXI_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_2_IS_DUAL 0


/* Definitions for peripheral AXI_GPIO_3 */
#define XPAR_AXI_GPIO_3_BASEADDR 0x40030000
#define XPAR_AXI_GPIO_3_HIGHADDR 0x4003FFFF
#define XPAR_AXI_GPIO_3_DEVICE_ID 3
#define XPAR_AXI_GPIO_3_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_3_IS_DUAL 0


/* Definitions for peripheral AXI_GPIO_4 */
#define XPAR_AXI_GPIO_4_BASEADDR 0x40040000
#define XPAR_AXI_GPIO_4_HIGHADDR 0x4004FFFF
#define XPAR_AXI_GPIO_4_DEVICE_ID 4
#define XPAR_AXI_GPIO_4_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_4_IS_DUAL 0


/* Definitions for peripheral V_PROC_SS_0_RESET_SEL_AXIS */
#define XPAR_V_PROC_SS_0_RESET_SEL_AXIS_BASEADDR 0x00010000
#define XPAR_V_PROC_SS_0_RESET_SEL_AXIS_HIGHADDR 0x0001FFFF
#define XPAR_V_PROC_SS_0_RESET_SEL_AXIS_DEVICE_ID 5
#define XPAR_V_PROC_SS_0_RESET_SEL_AXIS_INTERRUPT_PRESENT 0
#define XPAR_V_PROC_SS_0_RESET_SEL_AXIS_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_GPIO_0_BASEADDR 0x40000000
#define XPAR_GPIO_0_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_0_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_GPIO_1_BASEADDR 0x40010000
#define XPAR_GPIO_1_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_AXI_GPIO_1_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0

/* Canonical definitions for peripheral AXI_GPIO_2 */
#define XPAR_GPIO_2_BASEADDR 0x40020000
#define XPAR_GPIO_2_HIGHADDR 0x4002FFFF
#define XPAR_GPIO_2_DEVICE_ID XPAR_AXI_GPIO_2_DEVICE_ID
#define XPAR_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_GPIO_2_IS_DUAL 0

/* Canonical definitions for peripheral AXI_GPIO_3 */
#define XPAR_GPIO_3_BASEADDR 0x40030000
#define XPAR_GPIO_3_HIGHADDR 0x4003FFFF
#define XPAR_GPIO_3_DEVICE_ID XPAR_AXI_GPIO_3_DEVICE_ID
#define XPAR_GPIO_3_INTERRUPT_PRESENT 0
#define XPAR_GPIO_3_IS_DUAL 0

/* Canonical definitions for peripheral AXI_GPIO_4 */
#define XPAR_GPIO_4_BASEADDR 0x40040000
#define XPAR_GPIO_4_HIGHADDR 0x4004FFFF
#define XPAR_GPIO_4_DEVICE_ID XPAR_AXI_GPIO_4_DEVICE_ID
#define XPAR_GPIO_4_INTERRUPT_PRESENT 0
#define XPAR_GPIO_4_IS_DUAL 0

/* Canonical definitions for peripheral V_PROC_SS_0_RESET_SEL_AXIS */
#define XPAR_GPIO_5_BASEADDR 0x00010000
#define XPAR_GPIO_5_HIGHADDR 0x0001FFFF
#define XPAR_GPIO_5_DEVICE_ID XPAR_V_PROC_SS_0_RESET_SEL_AXIS_DEVICE_ID
#define XPAR_GPIO_5_INTERRUPT_PRESENT 0
#define XPAR_GPIO_5_IS_DUAL 0


/******************************************************************/

/* Definitions for driver HUD_GEN */
#define XPAR_XHUD_GEN_NUM_INSTANCES 1

/* Definitions for peripheral HUD_GEN_0 */
#define XPAR_HUD_GEN_0_DEVICE_ID 0
#define XPAR_HUD_GEN_0_S_AXI_AXILITES_BASEADDR 0x44AD0000
#define XPAR_HUD_GEN_0_S_AXI_AXILITES_HIGHADDR 0x44ADFFFF


/******************************************************************/

/* Canonical definitions for peripheral HUD_GEN_0 */
#define XPAR_XHUD_GEN_0_DEVICE_ID XPAR_HUD_GEN_0_DEVICE_ID
#define XPAR_XHUD_GEN_0_S_AXI_AXILITES_BASEADDR 0x44AD0000
#define XPAR_XHUD_GEN_0_S_AXI_AXILITES_HIGHADDR 0x44ADFFFF


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 3

/* Definitions for peripheral AXI_IIC_0 */
#define XPAR_AXI_IIC_0_DEVICE_ID 0
#define XPAR_AXI_IIC_0_BASEADDR 0x40800000
#define XPAR_AXI_IIC_0_HIGHADDR 0x4080FFFF
#define XPAR_AXI_IIC_0_TEN_BIT_ADR 0
#define XPAR_AXI_IIC_0_GPO_WIDTH 1


/* Definitions for peripheral AXI_IIC_1 */
#define XPAR_AXI_IIC_1_DEVICE_ID 1
#define XPAR_AXI_IIC_1_BASEADDR 0x40810000
#define XPAR_AXI_IIC_1_HIGHADDR 0x4081FFFF
#define XPAR_AXI_IIC_1_TEN_BIT_ADR 0
#define XPAR_AXI_IIC_1_GPO_WIDTH 1


/* Definitions for peripheral AXI_IIC_2 */
#define XPAR_AXI_IIC_2_DEVICE_ID 2
#define XPAR_AXI_IIC_2_BASEADDR 0x40820000
#define XPAR_AXI_IIC_2_HIGHADDR 0x4082FFFF
#define XPAR_AXI_IIC_2_TEN_BIT_ADR 0
#define XPAR_AXI_IIC_2_GPO_WIDTH 1


/******************************************************************/

/* Canonical definitions for peripheral AXI_IIC_0 */
#define XPAR_IIC_0_DEVICE_ID XPAR_AXI_IIC_0_DEVICE_ID
#define XPAR_IIC_0_BASEADDR 0x40800000
#define XPAR_IIC_0_HIGHADDR 0x4080FFFF
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 1

/* Canonical definitions for peripheral AXI_IIC_1 */
#define XPAR_IIC_1_DEVICE_ID XPAR_AXI_IIC_1_DEVICE_ID
#define XPAR_IIC_1_BASEADDR 0x40810000
#define XPAR_IIC_1_HIGHADDR 0x4081FFFF
#define XPAR_IIC_1_TEN_BIT_ADR 0
#define XPAR_IIC_1_GPO_WIDTH 1

/* Canonical definitions for peripheral AXI_IIC_2 */
#define XPAR_IIC_2_DEVICE_ID XPAR_AXI_IIC_2_DEVICE_ID
#define XPAR_IIC_2_BASEADDR 0x40820000
#define XPAR_IIC_2_HIGHADDR 0x4082FFFF
#define XPAR_IIC_2_TEN_BIT_ADR 0
#define XPAR_IIC_2_GPO_WIDTH 1


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 9
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID 0
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120FFFF
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0xFFFFFF00
#define XPAR_MICROBLAZE_0_AXI_INTC_HAS_FAST 1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RESET_VALUE 0x0000000000000010
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 9
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 32


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID
#define XPAR_MICROBLAZE_0_AXI_INTC_TYPE 0U
#define XPAR_AXI_TIMER_0_INTERRUPT_MASK 0X000001U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_INTR 0U
#define XPAR_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_MASK 0X000002U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR 1U
#define XPAR_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_MASK 0X000004U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR 2U
#define XPAR_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_MASK 0X000008U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR 3U
#define XPAR_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_MASK 0X000010U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR 4U
#define XPAR_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_MASK 0X000020U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR 5U
#define XPAR_AXI_IIC_0_IIC2INTC_IRPT_MASK 0X000040U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_IIC_0_IIC2INTC_IRPT_INTR 6U
#define XPAR_AXI_IIC_1_IIC2INTC_IRPT_MASK 0X000080U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_IIC_1_IIC2INTC_IRPT_INTR 7U
#define XPAR_AXI_UARTLITE_0_INTERRUPT_MASK 0X000100U
#define XPAR_MICROBLAZE_0_AXI_INTC_AXI_UARTLITE_0_INTERRUPT_INTR 8U

/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_MICROBLAZE_0_AXI_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000U
#define XPAR_INTC_0_HIGHADDR 0x4120FFFFU
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFF00U
#define XPAR_INTC_0_HAS_FAST 1U
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x0000000000000010U
#define XPAR_INTC_0_NUM_INTR_INPUTS 9U
#define XPAR_INTC_0_ADDR_WIDTH 32U
#define XPAR_INTC_0_INTC_TYPE 0U

#define XPAR_INTC_0_TMRCTR_0_INTERRUPT_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_INTR
#define XPAR_INTC_0_TMRCTR_0_INTERRUPT_LOW_PRIORITY_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR
#define XPAR_INTC_0_TMRCTR_0_INTERRUPT_LOW_PRIORITY_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR
#define XPAR_INTC_0_TMRCTR_0_INTERRUPT_LOW_PRIORITY_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR
#define XPAR_INTC_0_TMRCTR_0_INTERRUPT_LOW_PRIORITY_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR
#define XPAR_INTC_0_TMRCTR_0_INTERRUPT_LOW_PRIORITY_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_TIMER_0_INTERRUPT_LOW_PRIORITY_INTR
#define XPAR_INTC_0_IIC_0_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_IIC_0_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_1_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_IIC_1_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_UARTLITE_0_VEC_ID XPAR_MICROBLAZE_0_AXI_INTC_AXI_UARTLITE_0_INTERRUPT_INTR

/******************************************************************/

/* Definitions for driver MIG_7SERIES */
#define XPAR_XMIG7SERIES_NUM_INSTANCES 1U

/* Definitions for peripheral MIG_7SERIES_1 */
#define XPAR_MIG_7SERIES_1_DEVICE_ID 0U
#define XPAR_MIG_7SERIES_1_DDR3_ROW_WIDTH 15U
#define XPAR_MIG_7SERIES_1_DDR3_COL_WIDTH 0U
#define XPAR_MIG_7SERIES_1_DDR3_BANK_WIDTH 3U
#define XPAR_MIG_7SERIES_1_DDR3_DQ_WIDTH 16U


/******************************************************************/


/* Definitions for peripheral MIG_7SERIES_1 */
#define XPAR_MIG_7SERIES_1_BASEADDR 0x80000000
#define XPAR_MIG_7SERIES_1_HIGHADDR 0x87FFFFFF


/******************************************************************/

/* Canonical definitions for peripheral MIG_7SERIES_1 */
#define XPAR_MIG7SERIES_0_DEVICE_ID XPAR_MIG_7SERIES_1_DEVICE_ID
#define XPAR_MIG7SERIES_0_DDR_ROW_WIDTH 15U
#define XPAR_MIG7SERIES_0_DDR_COL_WIDTH 0U
#define XPAR_MIG7SERIES_0_DDR_BANK_WIDTH 3U
#define XPAR_MIG7SERIES_0_DDR_DQ_WIDTH 16U
#define XPAR_MIG7SERIES_0_BASEADDR 0x80000000U
#define XPAR_MIG7SERIES_0_HIGHADDR 0x87FFFFFFU


/******************************************************************/

/* Definitions for driver MIPICSISS */
#define XPAR_XCSISS_NUM_INSTANCES 1

/* Definitions for peripheral MIPI_CSI2_RX_SUBSYSTEM_0 */
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_BASEADDR 0x44A20000
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_HIGHADDR 0x44A3FFFF
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_DEVICE_ID 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_INC_IIC 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_NUM_LANES 2
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_NUM_PIXELS 2
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_PXL_FORMAT 0x2B
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_VC 4
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_BUF_DEPTH 1024
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_EMB_NON_IMG 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_DPY_EN_REG_IF 1
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_DPY_LINE_RATE 900
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_EN_CRC 1
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_EN_ACTIVELANES 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_EN_CSI_V2_0 0
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_EN_VCX 0


/******************************************************************/

/* Canonical definitions for peripheral MIPI_CSI2_RX_SUBSYSTEM_0 */
#define XPAR_CSISS_0_BASEADDR 0x44A20000
#define XPAR_CSISS_0_HIGHADDR 0x44A3FFFF
#define XPAR_CSISS_0_DEVICE_ID XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_DEVICE_ID
#define XPAR_CSISS_0_CMN_INC_IIC 0
#define XPAR_CSISS_0_CMN_NUM_LANES 2
#define XPAR_CSISS_0_CMN_NUM_PIXELS 2
#define XPAR_CSISS_0_CMN_PXL_FORMAT 0x2B
#define XPAR_CSISS_0_CMN_VC 16
#define XPAR_CSISS_0_CSI_BUF_DEPTH 1024
#define XPAR_CSISS_0_CSI_EMB_NON_IMG 0
#define XPAR_CSISS_0_DPY_EN_REG_IF 1
#define XPAR_CSISS_0_DPY_LINE_RATE 900
#define XPAR_CSISS_0_CSI_EN_CRC 1
#define XPAR_CSISS_0_CSI_EN_ACTIVELANES 0
#define XPAR_CSISS_0_EN_CSI_V2_0 0
#define XPAR_CSISS_0_EN_VCX 0


/******************************************************************/

/* Definitions for driver RGB2YCRCB */
#define XPAR_XRGB2YCRCB_NUM_INSTANCES 1

/* Definitions for peripheral V_RGB2YCRCB_0 */
#define XPAR_V_RGB2YCRCB_0_DEVICE_ID 0
#define XPAR_V_RGB2YCRCB_0_BASEADDR 0x44AC0000
#define XPAR_V_RGB2YCRCB_0_HIGHADDR 0x44ACFFFF
#define XPAR_V_RGB2YCRCB_0_S_AXIS_VIDEO_FORMAT 2
#define XPAR_V_RGB2YCRCB_0_M_AXIS_VIDEO_FORMAT 1
#define XPAR_V_RGB2YCRCB_0_HAS_DEBUG 0
#define XPAR_V_RGB2YCRCB_0_HAS_INTC_IF 0
#define XPAR_V_RGB2YCRCB_0_MAX_COLS 1920
#define XPAR_V_RGB2YCRCB_0_ACTIVE_COLS 1920
#define XPAR_V_RGB2YCRCB_0_ACTIVE_ROWS 1080
#define XPAR_V_RGB2YCRCB_0_HAS_CLIP 1
#define XPAR_V_RGB2YCRCB_0_HAS_CLAMP 1
#define XPAR_V_RGB2YCRCB_0_ACOEF 19595
#define XPAR_V_RGB2YCRCB_0_BCOEF 7471
#define XPAR_V_RGB2YCRCB_0_CCOEF 57493
#define XPAR_V_RGB2YCRCB_0_DCOEF 32250
#define XPAR_V_RGB2YCRCB_0_YOFFSET 16
#define XPAR_V_RGB2YCRCB_0_CBOFFSET 128
#define XPAR_V_RGB2YCRCB_0_CROFFSET 128
#define XPAR_V_RGB2YCRCB_0_YMAX 240
#define XPAR_V_RGB2YCRCB_0_YMIN 16
#define XPAR_V_RGB2YCRCB_0_CBMAX 240
#define XPAR_V_RGB2YCRCB_0_CBMIN 16
#define XPAR_V_RGB2YCRCB_0_CRMAX 240
#define XPAR_V_RGB2YCRCB_0_CRMIN 16
#define XPAR_V_RGB2YCRCB_0_S_AXI_CLK_FREQ_HZ 100000000
#define XPAR_V_RGB2YCRCB_0_STANDARD_SEL 0
#define XPAR_V_RGB2YCRCB_0_OUTPUT_RANGE 0


/******************************************************************/

/* Canonical definitions for peripheral V_RGB2YCRCB_0 */
#define XPAR_RGB2YCRCB_0_DEVICE_ID XPAR_V_RGB2YCRCB_0_DEVICE_ID
#define XPAR_RGB2YCRCB_0_BASEADDR 0x44AC0000
#define XPAR_RGB2YCRCB_0_HIGHADDR 0x44ACFFFF
#define XPAR_RGB2YCRCB_0_S_AXIS_VIDEO_FORMAT 2
#define XPAR_RGB2YCRCB_0_M_AXIS_VIDEO_FORMAT 1
#define XPAR_RGB2YCRCB_0_HAS_DEBUG 0
#define XPAR_RGB2YCRCB_0_HAS_INTC_IF 0
#define XPAR_RGB2YCRCB_0_MAX_COLS 1920
#define XPAR_RGB2YCRCB_0_ACTIVE_COLS 1920
#define XPAR_RGB2YCRCB_0_ACTIVE_ROWS 1080
#define XPAR_RGB2YCRCB_0_HAS_CLIP 1
#define XPAR_RGB2YCRCB_0_HAS_CLAMP 1
#define XPAR_RGB2YCRCB_0_ACOEF 19595
#define XPAR_RGB2YCRCB_0_BCOEF 7471
#define XPAR_RGB2YCRCB_0_CCOEF 57493
#define XPAR_RGB2YCRCB_0_DCOEF 32250
#define XPAR_RGB2YCRCB_0_YOFFSET 16
#define XPAR_RGB2YCRCB_0_CBOFFSET 128
#define XPAR_RGB2YCRCB_0_CROFFSET 128
#define XPAR_RGB2YCRCB_0_YMAX 240
#define XPAR_RGB2YCRCB_0_YMIN 16
#define XPAR_RGB2YCRCB_0_CBMAX 240
#define XPAR_RGB2YCRCB_0_CBMIN 16
#define XPAR_RGB2YCRCB_0_CRMAX 240
#define XPAR_RGB2YCRCB_0_CRMIN 16
#define XPAR_RGB2YCRCB_0_S_AXI_CLK_FREQ_HZ 100000000
#define XPAR_RGB2YCRCB_0_STANDARD_SEL 0
#define XPAR_RGB2YCRCB_0_OUTPUT_RANGE 0


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_TIMER_0 */
#define XPAR_AXI_TIMER_0_DEVICE_ID 0U
#define XPAR_AXI_TIMER_0_BASEADDR 0x41C00000U
#define XPAR_AXI_TIMER_0_HIGHADDR 0x41C0FFFFU
#define XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ 75000000U


/******************************************************************/

/* Canonical definitions for peripheral AXI_TIMER_0 */
#define XPAR_TMRCTR_0_DEVICE_ID 0U
#define XPAR_TMRCTR_0_BASEADDR 0x41C00000U
#define XPAR_TMRCTR_0_HIGHADDR 0x41C0FFFFU
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ

/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_DEVICE_ID 0U
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000U
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060FFFFU
#define XPAR_AXI_UARTLITE_0_BAUDRATE 9600U
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0U
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0U
#define XPAR_AXI_UARTLITE_0_DATA_BITS 8U

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_UARTLITE_0_DEVICE_ID 0U
#define XPAR_UARTLITE_0_BASEADDR 0x40600000U
#define XPAR_UARTLITE_0_HIGHADDR 0x4060FFFFU
#define XPAR_UARTLITE_0_BAUDRATE 9600U
#define XPAR_UARTLITE_0_USE_PARITY 0U
#define XPAR_UARTLITE_0_ODD_PARITY 0U
#define XPAR_UARTLITE_0_DATA_BITS 8U


/******************************************************************/
/* Definitions for driver V_DEMOSAIC */
#define XPAR_XV_DEMOSAIC_NUM_INSTANCES 1

/* Definitions for peripheral V_DEMOSAIC_0 */
#define XPAR_V_DEMOSAIC_0_DEVICE_ID 0
#define XPAR_V_DEMOSAIC_0_S_AXI_CTRL_BASEADDR 0x44A60000
#define XPAR_V_DEMOSAIC_0_S_AXI_CTRL_HIGHADDR 0x44A6FFFF
#define XPAR_V_DEMOSAIC_0_SAMPLES_PER_CLOCK 2
#define XPAR_V_DEMOSAIC_0_MAX_COLS 3840
#define XPAR_V_DEMOSAIC_0_MAX_ROWS 2160
#define XPAR_V_DEMOSAIC_0_MAX_DATA_WIDTH 8
#define XPAR_V_DEMOSAIC_0_ALGORITHM 0


/******************************************************************/

/* Canonical definitions for peripheral V_DEMOSAIC_0 */
#define XPAR_XV_DEMOSAIC_0_DEVICE_ID XPAR_V_DEMOSAIC_0_DEVICE_ID
#define XPAR_XV_DEMOSAIC_0_S_AXI_CTRL_BASEADDR 0x44A60000
#define XPAR_XV_DEMOSAIC_0_S_AXI_CTRL_HIGHADDR 0x44A6FFFF
#define XPAR_XV_DEMOSAIC_0_SAMPLES_PER_CLOCK 2
#define XPAR_XV_DEMOSAIC_0_MAX_COLS 3840
#define XPAR_XV_DEMOSAIC_0_MAX_ROWS 2160
#define XPAR_XV_DEMOSAIC_0_MAX_DATA_WIDTH 8
#define XPAR_XV_DEMOSAIC_0_ALGORITHM 0


/******************************************************************/

/* Definitions for driver V_HSCALER */
#define XPAR_XV_HSCALER_NUM_INSTANCES 1

/* Definitions for peripheral V_PROC_SS_0_HSC */
#define XPAR_V_PROC_SS_0_HSC_DEVICE_ID 0
#define XPAR_V_PROC_SS_0_HSC_S_AXI_CTRL_BASEADDR 0x00000000
#define XPAR_V_PROC_SS_0_HSC_S_AXI_CTRL_HIGHADDR 0x0000FFFF
#define XPAR_V_PROC_SS_0_HSC_SAMPLES_PER_CLOCK 1
#define XPAR_V_PROC_SS_0_HSC_NUM_VIDEO_COMPONENTS 3
#define XPAR_V_PROC_SS_0_HSC_MAX_COLS 4096
#define XPAR_V_PROC_SS_0_HSC_MAX_ROWS 2160
#define XPAR_V_PROC_SS_0_HSC_MAX_DATA_WIDTH 8
#define XPAR_V_PROC_SS_0_HSC_PHASE_SHIFT 6
#define XPAR_V_PROC_SS_0_HSC_SCALE_MODE 2
#define XPAR_V_PROC_SS_0_HSC_TAPS 8
#define XPAR_V_PROC_SS_0_HSC_ENABLE_422 0
#define XPAR_V_PROC_SS_0_HSC_ENABLE_420 0
#define XPAR_V_PROC_SS_0_HSC_ENABLE_CSC 0


/******************************************************************/

/* Canonical definitions for peripheral V_PROC_SS_0_HSC */
#define XPAR_XV_HSCALER_0_DEVICE_ID XPAR_V_PROC_SS_0_HSC_DEVICE_ID
#define XPAR_XV_HSCALER_0_S_AXI_CTRL_BASEADDR 0x00000000
#define XPAR_XV_HSCALER_0_S_AXI_CTRL_HIGHADDR 0x0000FFFF
#define XPAR_XV_HSCALER_0_SAMPLES_PER_CLOCK 1
#define XPAR_XV_HSCALER_0_NUM_VIDEO_COMPONENTS 3
#define XPAR_XV_HSCALER_0_MAX_COLS 4096
#define XPAR_XV_HSCALER_0_MAX_ROWS 2160
#define XPAR_XV_HSCALER_0_MAX_DATA_WIDTH 8
#define XPAR_XV_HSCALER_0_PHASE_SHIFT 6
#define XPAR_XV_HSCALER_0_SCALE_MODE 2
#define XPAR_XV_HSCALER_0_TAPS 8
#define XPAR_XV_HSCALER_0_ENABLE_422 0
#define XPAR_XV_HSCALER_0_ENABLE_420 0
#define XPAR_XV_HSCALER_0_ENABLE_CSC 0


/******************************************************************/

/* Definitions for driver V_MIX */
#define XPAR_XV_MIX_NUM_INSTANCES 1

/* Definitions for peripheral V_MIX_0 */
#define XPAR_V_MIX_0_DEVICE_ID 0
#define XPAR_V_MIX_0_S_AXI_CTRL_BASEADDR 0x44AE0000
#define XPAR_V_MIX_0_S_AXI_CTRL_HIGHADDR 0x44AEFFFF
#define XPAR_V_MIX_0_SAMPLES_PER_CLOCK 1
#define XPAR_V_MIX_0_MAX_COLS 1920
#define XPAR_V_MIX_0_MAX_ROWS 1080
#define XPAR_V_MIX_0_MAX_DATA_WIDTH 8
#define XPAR_V_MIX_0_VIDEO_FORMAT 0
#define XPAR_V_MIX_0_NR_LAYERS 2
#define XPAR_V_MIX_0_LOGO_LAYER 0
#define XPAR_V_MIX_0_MAX_LOGO_COLS 64
#define XPAR_V_MIX_0_MAX_LOGO_ROWS 64
#define XPAR_V_MIX_0_LOGO_TRANSPARENCY_COLOR 0
#define XPAR_V_MIX_0_LOGO_PIXEL_ALPHA 0
#define XPAR_V_MIX_0_LAYER1_ALPHA 1
#define XPAR_V_MIX_0_LAYER2_ALPHA 0
#define XPAR_V_MIX_0_LAYER3_ALPHA 0
#define XPAR_V_MIX_0_LAYER4_ALPHA 0
#define XPAR_V_MIX_0_LAYER5_ALPHA 0
#define XPAR_V_MIX_0_LAYER6_ALPHA 0
#define XPAR_V_MIX_0_LAYER7_ALPHA 0
#define XPAR_V_MIX_0_LAYER8_ALPHA 0
#define XPAR_V_MIX_0_LAYER9_ALPHA 0
#define XPAR_V_MIX_0_LAYER10_ALPHA 0
#define XPAR_V_MIX_0_LAYER11_ALPHA 0
#define XPAR_V_MIX_0_LAYER12_ALPHA 0
#define XPAR_V_MIX_0_LAYER13_ALPHA 0
#define XPAR_V_MIX_0_LAYER14_ALPHA 0
#define XPAR_V_MIX_0_LAYER15_ALPHA 0
#define XPAR_V_MIX_0_LAYER16_ALPHA 0
#define XPAR_V_MIX_0_LAYER1_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER2_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER3_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER4_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER5_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER6_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER7_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER8_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER9_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER10_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER11_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER12_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER13_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER14_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER15_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER16_UPSAMPLE 0
#define XPAR_V_MIX_0_LAYER1_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER2_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER3_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER4_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER5_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER6_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER7_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER8_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER9_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER10_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER11_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER12_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER13_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER14_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER15_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER16_MAX_WIDTH 1920
#define XPAR_V_MIX_0_LAYER1_INTF_TYPE 1
#define XPAR_V_MIX_0_LAYER2_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER3_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER4_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER5_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER6_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER7_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER8_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER9_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER10_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER11_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER12_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER13_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER14_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER15_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER16_INTF_TYPE 0
#define XPAR_V_MIX_0_LAYER1_VIDEO_FORMAT 5
#define XPAR_V_MIX_0_LAYER2_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER3_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER4_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER5_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER6_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER7_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER8_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER9_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER10_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER11_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER12_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER13_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER14_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER15_VIDEO_FORMAT 10
#define XPAR_V_MIX_0_LAYER16_VIDEO_FORMAT 10


/******************************************************************/

/* Canonical definitions for peripheral V_MIX_0 */
#define XPAR_XV_MIX_0_DEVICE_ID XPAR_V_MIX_0_DEVICE_ID
#define XPAR_XV_MIX_0_S_AXI_CTRL_BASEADDR 0x44AE0000
#define XPAR_XV_MIX_0_S_AXI_CTRL_HIGHADDR 0x44AEFFFF
#define XPAR_XV_MIX_0_SAMPLES_PER_CLOCK 1
#define XPAR_XV_MIX_0_MAX_COLS 1920
#define XPAR_XV_MIX_0_MAX_ROWS 1080
#define XPAR_XV_MIX_0_MAX_DATA_WIDTH 8
#define XPAR_XV_MIX_0_VIDEO_FORMAT 0
#define XPAR_XV_MIX_0_NR_LAYERS 2
#define XPAR_XV_MIX_0_LOGO_LAYER 0
#define XPAR_XV_MIX_0_MAX_LOGO_COLS 64
#define XPAR_XV_MIX_0_MAX_LOGO_ROWS 64
#define XPAR_XV_MIX_0_LOGO_TRANSPARENCY_COLOR false
#define XPAR_XV_MIX_0_LOGO_PIXEL_ALPHA false
#define XPAR_XV_MIX_0_LAYER1_ALPHA 1
#define XPAR_XV_MIX_0_LAYER2_ALPHA 0
#define XPAR_XV_MIX_0_LAYER3_ALPHA 0
#define XPAR_XV_MIX_0_LAYER4_ALPHA 0
#define XPAR_XV_MIX_0_LAYER5_ALPHA 0
#define XPAR_XV_MIX_0_LAYER6_ALPHA 0
#define XPAR_XV_MIX_0_LAYER7_ALPHA 0
#define XPAR_XV_MIX_0_LAYER8_ALPHA 0
#define XPAR_XV_MIX_0_LAYER9_ALPHA 0
#define XPAR_XV_MIX_0_LAYER10_ALPHA 0
#define XPAR_XV_MIX_0_LAYER11_ALPHA 0
#define XPAR_XV_MIX_0_LAYER12_ALPHA 0
#define XPAR_XV_MIX_0_LAYER13_ALPHA 0
#define XPAR_XV_MIX_0_LAYER14_ALPHA 0
#define XPAR_XV_MIX_0_LAYER15_ALPHA 0
#define XPAR_XV_MIX_0_LAYER16_ALPHA 0
#define XPAR_XV_MIX_0_LAYER1_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER2_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER3_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER4_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER5_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER6_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER7_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER8_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER9_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER10_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER11_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER12_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER13_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER14_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER15_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER16_UPSAMPLE 0
#define XPAR_XV_MIX_0_LAYER1_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER2_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER3_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER4_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER5_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER6_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER7_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER8_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER9_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER10_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER11_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER12_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER13_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER14_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER15_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER16_MAX_WIDTH 1920
#define XPAR_XV_MIX_0_LAYER1_INTF_TYPE 1
#define XPAR_XV_MIX_0_LAYER2_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER3_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER4_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER5_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER6_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER7_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER8_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER9_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER10_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER11_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER12_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER13_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER14_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER15_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER16_INTF_TYPE 0
#define XPAR_XV_MIX_0_LAYER1_VIDEO_FORMAT 5
#define XPAR_XV_MIX_0_LAYER2_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER3_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER4_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER5_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER6_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER7_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER8_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER9_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER10_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER11_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER12_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER13_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER14_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER15_VIDEO_FORMAT 10
#define XPAR_XV_MIX_0_LAYER16_VIDEO_FORMAT 10


/******************************************************************/

/* Definitions for driver V_TPG */
#define XPAR_XV_TPG_NUM_INSTANCES 1

/* Definitions for peripheral V_TPG_0 */
#define XPAR_V_TPG_0_DEVICE_ID 0
#define XPAR_V_TPG_0_S_AXI_CTRL_BASEADDR 0x44A70000
#define XPAR_V_TPG_0_S_AXI_CTRL_HIGHADDR 0x44A7FFFF
#define XPAR_V_TPG_0_HAS_AXI4S_SLAVE 1
#define XPAR_V_TPG_0_SAMPLES_PER_CLOCK 1
#define XPAR_V_TPG_0_NUM_VIDEO_COMPONENTS 3
#define XPAR_V_TPG_0_MAX_COLS 4096
#define XPAR_V_TPG_0_MAX_ROWS 2160
#define XPAR_V_TPG_0_MAX_DATA_WIDTH 8
#define XPAR_V_TPG_0_SOLID_COLOR 1
#define XPAR_V_TPG_0_RAMP 1
#define XPAR_V_TPG_0_COLOR_BAR 1
#define XPAR_V_TPG_0_DISPLAY_PORT 0
#define XPAR_V_TPG_0_COLOR_SWEEP 1
#define XPAR_V_TPG_0_ZONE_PLATE 0
#define XPAR_V_TPG_0_FOREGROUND 0


/******************************************************************/

/* Canonical definitions for peripheral V_TPG_0 */
#define XPAR_XV_TPG_0_DEVICE_ID XPAR_V_TPG_0_DEVICE_ID
#define XPAR_XV_TPG_0_S_AXI_CTRL_BASEADDR 0x44A70000
#define XPAR_XV_TPG_0_S_AXI_CTRL_HIGHADDR 0x44A7FFFF
#define XPAR_XV_TPG_0_HAS_AXI4S_SLAVE 1
#define XPAR_XV_TPG_0_SAMPLES_PER_CLOCK 1
#define XPAR_XV_TPG_0_NUM_VIDEO_COMPONENTS 3
#define XPAR_XV_TPG_0_MAX_COLS 4096
#define XPAR_XV_TPG_0_MAX_ROWS 2160
#define XPAR_XV_TPG_0_MAX_DATA_WIDTH 8
#define XPAR_XV_TPG_0_SOLID_COLOR 1
#define XPAR_XV_TPG_0_RAMP 1
#define XPAR_XV_TPG_0_COLOR_BAR 1
#define XPAR_XV_TPG_0_DISPLAY_PORT 0
#define XPAR_XV_TPG_0_COLOR_SWEEP 1
#define XPAR_XV_TPG_0_ZONE_PLATE 0
#define XPAR_XV_TPG_0_FOREGROUND 0


/******************************************************************/

/* Definitions for driver V_VSCALER */
#define XPAR_XV_VSCALER_NUM_INSTANCES 1

/* Definitions for peripheral V_PROC_SS_0_VSC */
#define XPAR_V_PROC_SS_0_VSC_DEVICE_ID 0
#define XPAR_V_PROC_SS_0_VSC_S_AXI_CTRL_BASEADDR 0x00020000
#define XPAR_V_PROC_SS_0_VSC_S_AXI_CTRL_HIGHADDR 0x0002FFFF
#define XPAR_V_PROC_SS_0_VSC_SAMPLES_PER_CLOCK 1
#define XPAR_V_PROC_SS_0_VSC_NUM_VIDEO_COMPONENTS 3
#define XPAR_V_PROC_SS_0_VSC_MAX_COLS 4096
#define XPAR_V_PROC_SS_0_VSC_MAX_ROWS 2160
#define XPAR_V_PROC_SS_0_VSC_MAX_DATA_WIDTH 8
#define XPAR_V_PROC_SS_0_VSC_PHASE_SHIFT 6
#define XPAR_V_PROC_SS_0_VSC_SCALE_MODE 2
#define XPAR_V_PROC_SS_0_VSC_TAPS 8
#define XPAR_V_PROC_SS_0_VSC_ENABLE_420 0


/******************************************************************/

/* Canonical definitions for peripheral V_PROC_SS_0_VSC */
#define XPAR_XV_VSCALER_0_DEVICE_ID XPAR_V_PROC_SS_0_VSC_DEVICE_ID
#define XPAR_XV_VSCALER_0_S_AXI_CTRL_BASEADDR 0x00020000
#define XPAR_XV_VSCALER_0_S_AXI_CTRL_HIGHADDR 0x0002FFFF
#define XPAR_XV_VSCALER_0_SAMPLES_PER_CLOCK 1
#define XPAR_XV_VSCALER_0_NUM_VIDEO_COMPONENTS 3
#define XPAR_XV_VSCALER_0_MAX_COLS 4096
#define XPAR_XV_VSCALER_0_MAX_ROWS 2160
#define XPAR_XV_VSCALER_0_MAX_DATA_WIDTH 8
#define XPAR_XV_VSCALER_0_PHASE_SHIFT 6
#define XPAR_XV_VSCALER_0_SCALE_MODE 2
#define XPAR_XV_VSCALER_0_TAPS 8
#define XPAR_XV_VSCALER_0_ENABLE_420 0


/******************************************************************/

/* Definitions for driver VPROCSS */
#define XPAR_XVPROCSS_NUM_INSTANCES 1

/* Definitions for peripheral V_PROC_SS_0 */
#define XPAR_V_PROC_SS_0_BASEADDR 0x44A80000
#define XPAR_V_PROC_SS_0_HIGHADDR 0x44ABFFFF
#define XPAR_V_PROC_SS_0_DEVICE_ID 0
#define XPAR_V_PROC_SS_0_SCALER_ALGORITHM 2
#define XPAR_V_PROC_SS_0_TOPOLOGY 0
#define XPAR_V_PROC_SS_0_SAMPLES_PER_CLK 1
#define XPAR_V_PROC_SS_0_MAX_DATA_WIDTH 8
#define XPAR_V_PROC_SS_0_NUM_VIDEO_COMPONENTS 3
#define XPAR_V_PROC_SS_0_MAX_COLS 4096
#define XPAR_V_PROC_SS_0_MAX_ROWS 2160
#define XPAR_V_PROC_SS_0_H_SCALER_TAPS 8
#define XPAR_V_PROC_SS_0_V_SCALER_TAPS 8
#define XPAR_V_PROC_SS_0_H_SCALER_PHASES 64
#define XPAR_V_PROC_SS_0_V_SCALER_PHASES 64
#define XPAR_V_PROC_SS_0_CHROMA_ALGORITHM 2
#define XPAR_V_PROC_SS_0_H_CHROMA_TAPS 4
#define XPAR_V_PROC_SS_0_V_CHROMA_TAPS 4
#define XPAR_V_PROC_SS_0_DEINT_MOTION_ADAPTIVE 1


/******************************************************************/

/* Canonical definitions for peripheral V_PROC_SS_0 */
#define XPAR_XVPROCSS_0_BASEADDR 0x44A80000
#define XPAR_XVPROCSS_0_HIGHADDR 0x44ABFFFF
#define XPAR_XVPROCSS_0_DEVICE_ID XPAR_V_PROC_SS_0_DEVICE_ID
#define XPAR_XVPROCSS_0_SCALER_ALGORITHM 2
#define XPAR_XVPROCSS_0_TOPOLOGY 0
#define XPAR_XVPROCSS_0_SAMPLES_PER_CLK 1
#define XPAR_XVPROCSS_0_MAX_DATA_WIDTH 8
#define XPAR_XVPROCSS_0_NUM_VIDEO_COMPONENTS 3
#define XPAR_XVPROCSS_0_MAX_COLS 4096
#define XPAR_XVPROCSS_0_MAX_ROWS 2160
#define XPAR_XVPROCSS_0_H_SCALER_TAPS 8
#define XPAR_XVPROCSS_0_V_SCALER_TAPS 8
#define XPAR_XVPROCSS_0_H_SCALER_PHASES 64
#define XPAR_XVPROCSS_0_V_SCALER_PHASES 64
#define XPAR_XVPROCSS_0_CHROMA_ALGORITHM 2
#define XPAR_XVPROCSS_0_H_CHROMA_TAPS 4
#define XPAR_XVPROCSS_0_V_CHROMA_TAPS 4
#define XPAR_XVPROCSS_0_DEINT_MOTION_ADAPTIVE 1


/******************************************************************/

/* Definitions for driver VTC */
#define XPAR_XVTC_NUM_INSTANCES 1

/* Definitions for peripheral V_TC_0 */
#define XPAR_V_TC_0_DEVICE_ID 0
#define XPAR_V_TC_0_BASEADDR 0x44A00000
#define XPAR_V_TC_0_HIGHADDR 0x44A0FFFF
#define XPAR_V_TC_0_GENERATE_EN 1
#define XPAR_V_TC_0_DETECT_EN 0
#define XPAR_V_TC_0_DET_HSYNC_EN 1
#define XPAR_V_TC_0_DET_VSYNC_EN 1
#define XPAR_V_TC_0_DET_HBLANK_EN 1
#define XPAR_V_TC_0_DET_VBLANK_EN 1
#define XPAR_V_TC_0_DET_AVIDEO_EN 1
#define XPAR_V_TC_0_DET_ACHROMA_EN 0


/******************************************************************/

/* Canonical definitions for peripheral V_TC_0 */
#define XPAR_VTC_0_DEVICE_ID XPAR_V_TC_0_DEVICE_ID
#define XPAR_VTC_0_BASEADDR 0x44A00000
#define XPAR_VTC_0_HIGHADDR 0x44A0FFFF
#define XPAR_VTC_0_GENERATE_EN 1
#define XPAR_VTC_0_DETECT_EN 0
#define XPAR_VTC_0_DET_HSYNC_EN 1
#define XPAR_VTC_0_DET_VSYNC_EN 1
#define XPAR_VTC_0_DET_HBLANK_EN 1
#define XPAR_VTC_0_DET_VBLANK_EN 1
#define XPAR_VTC_0_DET_AVIDEO_EN 1
#define XPAR_VTC_0_DET_ACHROMA_EN 0


/******************************************************************/

#endif  /* end of protection macro */
